recipe_scrapers/bbcfood.py
This commit fixes the BBC food parser which is currently broken (see issue #12 ). The fix is as simple as switching to the new itemprop attribute rather than the old classes.
There are new classes we could be using, but it seems like itemprop is the primary identifier for the field and more readable.
=> Fix BBC Food, resolves #12

recipe_scrapers/__init__.py
to additionally raise a custom WebsiteNotImplementedError exception.  I think this helps make the library slightly more user friendly.
Example Code:
```
from recipe_scrapers import scrape_me
scrape_me("http://www.cnn.com")
```
Current behavior:
```
KeyError: 'cnn.com'
```
With this pull request the new behavior:
```
KeyError: 'cnn.com'
During handling of the above exception, another exception occurred:
WebsiteNotImplementedError: Website (cnn.com) is not supported
```
=> Change behavior for an unsupported website

recipe_scrapers/giallozafferano.py
The scraper cannot parse the ingredients of all recipes since the list is not always within a dd element but sometimes it is a simple collection of li elements. Here an example: https://ricette.giallozafferano.it/Parmigiana-di-melanzane.html
The modification I proposed should solve this issue: during my tests the recipes that previously had an empty list of ingredients now contain all the ingredients.
=> giallozafferano ingredients list

README.rst
There were a few links that were broken and needed to be fixed in the README.
foodnetwork.com
foodrepublic.com
giallozafferano.it
=> Broken links in README.rst

.vscode/settings.json, recipe_scrapers/__init__.py, recipe_scrapers/_schemaorg.py, recipe_scrapers/tests/test_schemaorg.py, requirements.txt, tests.py
Why use custom scraping logic when you can pull the data you are looking for directly from the Recipe schema object if it's present at the site? This change would mean the schema method would be preferred but I think that's the best way to ensure the data is accurate. It also would expand your supported sites pretty significantly (from what I've seen, almost all recipe sites embed it because it's required to show rich search results in Google).
=> Add ability to use schema.org Recipe schema to expand site support

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/_utils.py, recipe_scrapers/marmiton.py, recipe_scrapers/tests/test_data/marmiton.testhtml, recipe_scrapers/tests/test_marmiton.py, tests.py
Hello :-) 
Here a scraper for _marmiton_, a good French recipes website.
Chiara
=> Add marmiton scraper

recipe_scrapers/__init__.py, setup.py
Sometimes it can be handy to inspect the version of a library after importing it - [PEP 396](https://www.python.org/dev/peps/pep-0396/) documents a standard way to do this.  After this change, you can run:
```python
>>> import recipe_scrapers
>>> recipe_scrapers.__version__
'8.1.0'
```
Pretty minor, but sometimes useful!
=> Add PEP-396 module version number

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/new_scraper.md, .github/ISSUE_TEMPLATE/scraper_bug_report.md
It's a little tricky to test these before they're merged into to the GitHub repo, as far as I know - and maybe the issue report volume is still low enough that we don't really need them yet.  But I figured they might be helpful.  What do you think about the idea and tone of these, @bfcarpio @hhursev? 
Here are a couple of references from GitHub's documentation about issue / PR templates:
- https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
- https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
Resolves #146
=> Suggest GitHub issue templates for recipe-scrapers library

.flake8, .pre-commit-config.yaml, recipe_scrapers/_abstract.py, recipe_scrapers/bbcfood.py, recipe_scrapers/eatsmarter.py, recipe_scrapers/hellofresh.py, recipe_scrapers/mindmegette.py, requirements.txt
A Therapeutic PR because guess what caused problems recently at work...
The official Python 3 documentation [doesn't recommend](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting) printf-style string formatting:
> The formatting operations described here exhibit a variety of quirks that
> lead to a number of common errors (such as failing to display tuples and
> dictionaries correctly). Using the newer formatted string literals,
> the `str.format` interface, or template strings may help avoid these errors.
> Each of these alternatives provides their own trade-offs and benefits of simplicity,
> flexibility, and/or extensibility.
This PR fixes existing printf style formatting as well as adds a flake8 plugin that will throw warnings when it is used thus preventing …
=> Ban `printf` style formatting

requirements.txt, tests/__init__.py, tests/conftest.py
Sometimes the structure and content of web pages changes, and when that happens it has the potential to break scrapers (or perhaps worse, cause them to return incorrect data).
A quick way to verify this is to run 'online' scraper tests - i.e. retrieve the current web content corresponding to each test at runtime.
This change adds support for a `pytest` option -- `--online` - that can be specified at the command-line in order to enable online-test behaviour.
=> Allow running tests 'online'

recipe_scrapers/delish.py, tests/__init__.py, tests/test_data/delish_rogue_ol.testhtml, tests/test_delish.py
Some recipes on Delish have multiple `<ol>` tags in them, namely https://www.delish.com/cooking/recipe-ideas/a46303/baileys-cheesecake-recipe/ causing the instructions to not parse properly. This ensures the scraper finds the instructions properly.
I created a new test file for Delish and updated the base test class to allow specifying the file name of the test data.
=> Fixing Delish Scraper failing with random <ol>

recipe_scrapers/__init__.py, setup.py
This is a non-user-facing change to swap out the existing [`tldextract`](https://pypi.org/project/tldextract/) library for the [`tld`](https://pypi.org/project/tld/) library instead.
I was looking into updating to the latest `tldextract` version as part of keeping dependencies fresh, and noticed that the constructor arguments for the `TLDExtract` class have been changing a bit over time, and in particular there is some caching/TLD update logic that requires pulling in the `requests` library, performing network connections, and writing cache contents.  I've provided some feedback in their issue tracker regarding the caching topic (basically suggesting re-use of existing libraries).
It's a little arbitrary, but `tld` seems lighter-weight and less dependency-burdened than `tldextract`, while …
=> Migrate to the 'tld' Python library

recipe_scrapers/epicurious.py
Scrapes the total time for the recipes in Epicurious that include it. For those that don't include it, returns 0 as it did previously.
=> Add total time for Epicurious

.pre-commit-config.yaml
Totally optional. I just used this tool to fix the many changes I made in #331 and thought it might be interesting to keep things organized in the automated way that we do.
=> Add isort to pre-commit

recipe_scrapers/plugins/_interface.py
We definitely don't need to instantiate this class.
I started to look at implementing my other things, but this is all I could do for now. Optional for v13
=> Make PluginInterface abstract

recipe_scrapers/_abstract.py
Some sites block old User Agents now, so bumped it to win10 Firefox. Not particular to this specific UA, but should probably be bumped to something equally new if not this one.
Example site (in `wild_mode=True` of course): [https://thenaturalnurturer.com/chickpea-vegetable-nuggets/](https://thenaturalnurturer.com/chickpea-vegetable-nuggets/)
=> Bump User Agent to win10 Firefox

recipe_scrapers/_schemaorg.py, tests/test_data/schemaorg.testhtml, tests/test_schemaorg.py
I don't think it makes sense to include nutrient field names where there is no value present.  In addition, `normalize_string` does not currently work correctly for inputs of type `NoneType`.  That method could do with some attention and perhaps be refactored out eventually.
=> Fixup: omit nutrient fields that have no value present

recipe_scrapers/_abstract.py, recipe_scrapers/_schemaorg.py
We currently skip assigning a `self.schema` attribute when `SchemaOrg` JSON parsing fails, but we don't check for presence of that attribute in the scraper code.  It might be safer to unconditionally store a `SchemaOrg` on each scraper -- even if that means it may contain empty parsing results.
The underlying `extruct` library call is updated to log parsing errors instead of throwing them as exceptions.
Relates to the thread at https://github.com/hhursev/recipe-scrapers/pull/286#issuecomment-753405193 (cc @adamkeys @hhursev)
=> SchemaOrg: adjust parser error handling

tests/__init__.py, tests/test_dr.py, tests/test_forksoverknives.py, tests/test_marthastewart.py, tests/test_nytimes.py, tests/test_thekitchn.py
It can be useful when investigating scraper test failures to have a complete diff displayed in the test failure logs.  Python's `unittest` library allows configuration of diff limits using the [`TestCase.maxDiff` setting](https://docs.python.org/3/library/unittest.html#unittest.TestCase.maxDiff).  Here we disable the diff limit at the base scraper level, so that the setting is applied to all scraper tests.
=> Unset maximum diff size for scraper tests

README.rst, recipe_scrapers/domesticateme.py, recipe_scrapers/heb.py, recipe_scrapers/streetkitchen.py, recipe_scrapers/wholefoods.py, tests/test_domesticateme.py, tests/test_heb.py, tests/test_streetkitchen.py, tests/test_wholefoods.py
This PR aims to close #414, where I described how removing prefixes could be beneficial for application developers.  
This was also highlighted in #399, where a user asked to add support for an existing website, which was rejected because the host wasn't matching.  
This was tested by applying the changes and manually importing a recipe from each of the touched scrapers, as well as updating the tests.  
```python
from recipe_scrapers import scrape_me
scrape_me('https://domesticate-me.com/asparagus-gratin/')
scrape_me('https://www.heb.com/recipe/recipe-item/grilled-s-more-dip/1398895332108')
```
I could not test `wholefoodmarkets.{com,co.uk}` because I'm in neither of these two regions and they're not available to me.
Thanks!
=> Clean hosts of prefixes

recipe_scrapers/_exceptions.py, tests/library/test_exceptions.py
Hi again,  
In this PR, I aim to fix two issues related to errors raised in the library.  
1) `WebsiteNotImplementedError` was missing `self.domain`.   
Thus, it used to raise an `AttributeError` when initialized:
```python
In [1]: from recipe_scrapers import scrape_me
In [2]: recipe = scrape_me('https://example.com/recipe/')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/gourmand/venv/lib/python3.9/site-packages/recipe_scrapers/__init__.py in scrape_me(url_path, **options)
KeyError: 'example.com'
During handling of the above exception, another exception occurred:
AttributeError                            Traceback (most recent call last)
<ipython-input-15-a004d3ee2fba> in <module> …
```
=> Add missing WebsiteNotImplementedError.domain property

recipe_scrapers/koket.py
Hi,
This PR fixes an unfortunate import in the `koket.se` scraper, introduced [here](https://github.com/hhursev/recipe-scrapers/commit/8500fd8e0f8a982325a2dc56b226416b749c5f7e).  
This also breaks the latest release.  
I tested this change by running `pytest -vv tests/` first, seeing the keket test fail, doing the change, and seeing all tests pass.  
I also checked that this fix makes my application start again.
Thanks!
Cyril
=> Fix re import in koket scraper

.github/ISSUE_TEMPLATE/new_scraper.md
This is to reduce the notion that only existing contributors / members of the `recipe-scrapers` repo can implement additional scrapers.  In practice we often receive pull requests for scrapers, and could/should use the 'help wanted' and 'good first issue' labels to help new contributors find ways they can get involved.
=> Substitute 'community' for 'team' in scraper request template

recipe_scrapers/__init__.py, recipe_scrapers/kptncook.py, tests/test_data/kptncook.testhtml, tests/test_kptncook.py
**example:** http://mobile.kptncook.com/recipe/pinterest/Low-Carb-Tarte-Flamb%C3%A9e-with-Serrano-Ham-%26-Cream-Cheese/315c3c32?lang=en
On the kptncook website the recipes are only provided in a redacted form (most of the instructions are missing) so that users are incentivized to install the app. 
However after analysing the app I found some API endpoints from which the whole recipe data can be requested as json. 
(My writedown of the results can be found here: https://github.com/gloriousDan/kptncook-api-reverse-engineering)
I hope that this is still in the scope of this scraping framework, since my implementation goes quite a long way from simple html scraping.
Since this is my first PR ever I'd love to get feedback on my implementation and the merging process :)
=> Add support for kptncook recipes

recipe_scrapers/__init__.py, recipe_scrapers/_abstract.py, recipe_scrapers/kptncook.py, tests/__init__.py, tests/test_wild_mode.py
Closes #472
This PR would add an additional top level package function that would allow users to pass the html directly to the. The `scrape_html` differs slightly from the `scrape_me` in that it automatically falls back to the wild mode if an `org_url` argument isn't provided.
It also simplifies some of the package testing by allowing the test cases to utilize the html option instead of overriding the settings.TEST_MODE variable. However the TEST_MODE variable is still needed in at least one case. 
I also wasn't able to run all the tests on my computer. I think it has to do with the M1 architecture not playing well with a dependency. I was able to verify the tests that do work on my machine continued to work. There may be some additionally test cases to fix in CI.
=> feat: allow scrape of html

recipe_scrapers/kptncook.py, recipe_scrapers/marleyspoon.py, requirements-dev.txt, tests/__init__.py, tests/test_data/foodnetwork.testhtml, tests/test_foodnetwork.py, tests/test_gousto.py, tests/test_kptncook.py, tests/test_marleyspoon.py
Roughly speaking, two significant changes here:
- Use the [`responses`](https://pypi.org/project/responses/) library to mock the result of HTTP requests, simplifying some of the unit test base class (83d96c1cd34d3848aff76f82a6d407228fa2f2c7)
- Allow unit tests to (optionally) mock multiple requests by overriding an `expected_requests` property (example: https://github.com/hhursev/recipe-scrapers/commit/e795707fb9e1769931ca46732202c3f60bc35ca0#diff-e58d4f5bec87567559c9de25b031039ff9ae89c4e3319b2224ae0dda3425a16fR14-R15)
The good and the bad:
- :heavy_plus_sign: Makes multi-request scrapers easier to test
- :heavy_minus_sign: Adds a dependency
- :heavy_minus_sign: Might not be as simple as possible - is it more complicated than the code was originally?
Resolves #550.
cc @hhursev @bfcarpio …
=> Refactor unit test data loading and request mocking

recipe_scrapers/__init__.py
Resolves an issue where the `scraper` variable could be accessed at https://github.com/hhursev/recipe-scrapers/blob/2e0d9680df5f83a1ecfb118012a2ddd7835c32cd/recipe_scrapers/__init__.py#L459 before it was declared (when [`host_name` is empty](https://github.com/hhursev/recipe-scrapers/blob/2e0d9680df5f83a1ecfb118012a2ddd7835c32cd/recipe_scrapers/__init__.py#L455))
=> Fixup: ensure 'scraper' variable is declared within scrape_html method

recipe_scrapers/kptncook.py
cc @gloriousDan - a small request consistency detail that I missed during previous review(s)
=> Consistency: use 'proxies' and 'timeout' arguments during kptncook scraper web requests

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/bettybossi.py, tests/test_bettybossi.py, tests/test_data/bettybossi.testhtml
The BettyBossi website was requested in #531 and stores its data in the json-ld format.  
However, the website implements a refresh
Here I propose a solution where the scraper first gets the page content using a `requests.Session`, then calls the parent's constructor providing the `html`.  
I tested this with the unit test and the following:  
```python
from recipe_scrapers import scrape_me
URL = https://www.bettybossi.ch/fr/Rezept/ShowRezept/BB_BLUB160501_0070A-40-fr
r = scrape_me(URL)
print(r.ingredients())
```  
On an unrelated note, I think that the type annotation for `AbstractScraper` might be wrong.  
According [to the source documentation](https://github.com/psf/requests/blob/73793ce43e3d940a0f8d6b9b8ff125617828d8a1/requests/sessions.py#L400), the proxies should be a `Dict[str, …
=> Add support for BettyBossi.ch

recipe_scrapers/_schemaorg.py, tests/test_comidinhasdochef.py
certain recipe pages don't yield proper results when parsed with wild mode even tough they have a microdata/json+ld schema.
The reason for that is that the schema function in `_schemaorg.py` iterates over the website data and stops iteration when it finds an entry of type `WebPage` even if a type `Recipe` comes afterwards. 
- rewrite the parsing function to consider schemas of all types and choose which suits the best afterwards
- order the schema list in the raw data so recipe always comes first
since i wasn't to familiar with the codebase i choose to implement the least intrusive method of ordering the schema data without changing any of the following logic.
this PR should significantly improve parsing results for wild_mode pages as many websites that contain a `WebPage` schema before a …
=> fixed wild mode for unordered schemas

recipe_scrapers/food.py, tests/test_food.py
fixes #590 
Changed the scraper for food.com from soup to schema
=> Fixed issue with food.com scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/owenhan.py, tests/test_data/owenhan.testhtml, tests/test_owenhan.py
This is my first time contributing. Please  let me know if there's any improvement to be made.
=> Added owen-han.com

tests/__init__.py
Re-introduce use of a file `open` [context manager](https://docs.python.org/3/reference/datamodel.html#context-managers) during unit test data loading to avoid noisy ResourceWarning output when running unit tests with `python -m unittest`
Fixes #608
=> Re-introduce use of a file open contextmanager during unit test data loading

.flake8
I am not sure if this issue is special to my setup as I run on a windows PC but I noticed two things
- the pre commit hook runs quite long
- if i run flake8 manually it shows me tons of warnings for things in `.venv`
this PR adds `./venv/*` to the ignored folders in the flake8 config. Since .venv is not in control of the project anyway it should not matter if flake is run there or not. 
This speeds up the pre commit hook significantly and prevents any error messages from venv library files
=> added .venv to flake8 ignored directories

recipe_scrapers/simplyrecipes.py, tests/test_data/simplyrecipes.testhtml, tests/test_simplyrecipes.py
Update the CSS class for ingredients. While here, also update the formatting of instructions such that colon isn't repeated twice. Refetch the test HTML file for verification.
Test: python -m coverage run -m unittest tests.test_simplyrecipes
=> Fix ingredients for simplyrecipes.com scraper

recipe_scrapers/_utils.py, setup.py, tests/library/test_utils.py
Use the `isodate` library to attempt to parse time durations from strings that look like potential ISO8601 date strings in `get_minutes` utility method.
Note that we already transitively depend on the `isodate` library (via `extruct -> rdflib -> isodate`).
The `get_minutes` method began failing a `flake8` complexity check after this functionality was added; that method would benefit from some simplification and refactoring (see #551).
Fixes #606.
=> Use isodate library to attempt ISO 8601 duration parsing in get_minutes

recipe_scrapers/cookstr.py, recipe_scrapers/cucchiaio.py, recipe_scrapers/nutritionbynathalie.py, recipe_scrapers/popsugar.py, recipe_scrapers/thespruceeats.py
The 'text' parameter is still provided by `bs4` but is deprecated; see https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/CHANGELOG#L546.
=> Maintenance: update bs4 string searches to use 'string' parameter instead of 'text'

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/rosannapansino.py, tests/test_data/rosannapansino.testhtml, tests/test_rosannapansino.py
closes #470 
hope to get a `hacktoberfest-accepted` label.
=> Add rosanna pansino

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/leanandgreenrecipes.py, tests/test_data/leanandgreenrecipes.testhtml, tests/test_leanandgreenrecipes.py
=> Add LeanAndGreenRecipes

.github/workflows/unittests.yaml
I had disabled Coveralls during #628 (a bugfix to make our continuous integration run as we intend on multiple operating systems) because I noticed that it looked like a token value was exposed.
This pull request re-enables coveralls - I'll also check whether it makes sense to enable parallel mode at the same time.
=> Continuous integration: re-enable coveralls test coverage upload

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/maangchi.py, tests/test_data/maangchi.testhtml, tests/test_maangchi.py
=> feat: add maangchi

README.rst, requirements-dev.txt, run_tests.py
Given the number of tests we run, this feels like it _should_ be useful in some circumstances.  But as part of #617 I'd like to try to reduce, clean up and modernize some of our dependencies, and then re-add complexity only where it proves valuable.
#648 was a sorta half-hearted attempt to discover continuous integration performance changes as a result of running tests in serial - it didn't really prove anything for/against though.
On the principle of simplification, I plan to move ahead with this - and if & when anyone disagrees, happy to restore it, although preferably with some supporting (and ideally ongoing) information to show that it's working.
=> Remove unittest-parallel dependency

.pre-commit-config.yaml, README.rst, generate.py, mypy.ini, recipe_scrapers/_utils.py, recipe_scrapers/bettybossi.py, recipe_scrapers/goustojson.py, recipe_scrapers/marleyspoon.py, recipe_scrapers/woolworths.py, requirements-dev.txt, tests/__init__.py, tests/test_foodnetwork.py, tests/test_gousto.py, tests/test_goustojson.py, tests/test_marleyspoon.py, tests/test_woolworths.py, tox.ini
- Use `pre-commit` to perform both `tox`-based and git-hook-based linting
- Add `mypy` to the `pre-commit` lint configuration
=> Consolidate linting configuration

recipe_scrapers/_schemaorg.py, recipe_scrapers/sallysblog.py
While refactoring some of the `schema.org` metadata handling, I found a couple of situations where we were overwriting the `data` attribute on `SchemaOrg` object instances with empty/falsy data.
=> Fixup: remove overwrite of schema.org data with 'mainEntity' contents during schema.org processing

tests/__init__.py, tests/test_farmhousedelivery_1.py, tests/test_farmhousedelivery_2.py, tests/test_finedininglovers_1.py, tests/test_finedininglovers_2.py, tests/test_foodnetwork.py, tests/test_gousto.py, tests/test_goustojson.py, tests/test_greatbritishchefs_1.py, tests/test_greatbritishchefs_2.py, tests/test_kptncook.py, tests/test_marleyspoon.py, tests/test_panelinha_1.py, tests/test_panelinha_2.py, tests/test_reishunger_1.py, tests/test_reishunger_2.py, tests/test_seriouseats_1.py, tests/test_seriouseats_2.py, tests/test_thehappyfoodie_1.py, tests/test_thehappyfoodie_2.py, tests/test_thespruceeats_1.py, tests/test_thespruceeats_2.py, tests/test_wild_mode.py, tests/test_woolworths.py
This significantly reduces the amount of time taken (and compute resource used) to run the unit test suite.
There's at least one tradeoff: it makes the test cases somewhat stateful (side-effects introduced during one test method could affect other test methods).
=> Unit tests: move scraper construction from setUp (per-method) to setUpClass (per-case)

recipe_scrapers/_schemaorg.py, recipe_scrapers/sallysblog.py
Although this change seemed fine going by the unit test results, I think there might be a less disruptive / more data-safe way to handle this.  `mainEntity` does seem valid for both `WebPage` and `Recipe` data.
Reverts hhursev/recipe-scrapers#666
=> Revert "Fixup: remove overwrite of schema.org data with 'mainEntity' contents during schema.org processing"

recipe_scrapers/_schemaorg.py
An attempt to simplify this part of the code while maintaining backwards compatibility.
There could be more stuff we could simplify/remove here.
=> Refactor: `schema.org` parser

.github/ISSUE_TEMPLATE/new_scraper.md, .github/ISSUE_TEMPLATE/scraper_bug_report.md
Relates to https://github.com/hhursev/recipe-scrapers/issues/617#issuecomment-1280024742.
Edit: link to specific commit instead of issue number.
=> Reduce the amount of wording in the GitHub 'new issue' templates

recipe_scrapers/lecker.py, tests/test_data/lecker_1.testhtml, tests/test_data/lecker_2.testhtml, tests/test_lecker_1.py, tests/test_lecker_2.py
fixes #448 by allowing to import body text of lecker de articles
lecker.de contains articles that are not formatted in a way that structured data can be extracted. This allows to load the data into the instructions so that a mostly useful recipe is returned.
=> Fix lecker.de articles

.pre-commit-config.yaml
=> pre-commit configuration: migrate source of flake8 from gitlab.com to github.com

tox.ini
`tox` version 1.0 onwards provides support for substitution of a `{posargs}` pattern in the `tox.ini` file.
This can allow callers to provide additional arguments to the `tox` environment command.
In the context of unit testing, that's often useful to specify test patterns to run - for example, by using `tox -e py -- -k <pattern>` to run only unit tests with names matched by `<pattern>`.
=> tox: permit positional arguments when running 'unittest'-based unit tests

recipe_scrapers/amazingribs.py, tests/test_amazingribs.py, tests/test_data/amazingribs.testhtml
The existing scraper mostly continued to work fine, although author attribution was incorrect for some pages.
Resolves #687.
=> Update amazingribs scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/projectgezond.py, tests/test_data/projectgezond.testhtml, tests/test_projectgezond.py
Thanks for this project! I use it a lot on my Mealie instance.
This PR contains a Dutch recipe site that I use sometimes ([Link](https://www.projectgezond.nl/)). Sadly the site did not have a nice way of using the schema nor did the HTML have useful class names, so my implementation might seem a bit hacky. 
Feedback is appreciated to improve the implementation!
=> Add Project Gezond scraper (Dutch Website)

.github/workflows/linters.yaml, .github/workflows/unittests.yaml, tox.ini
Attempts to resolve #698 using a short-term solution.
Bases upon #700 so that both install command configurations are consistent (and both are consistent with the `tox` default).
=> GitHub Actions workflows: version-constrain 'tox' to less-than v4

.github/workflows/linters.yaml, .github/workflows/unittests.yaml, tox.ini
Ideally, the goal here is to update `tox.ini` so that it's backwards-compatible with `tox` v3, while also allowing us to upgrade to `tox` v4 in the nearish future.
Relates to #698.
=> tox.ini: tox4 compatibility

recipe_scrapers/forksoverknives.py, tests/test_data/forksoverknives.testhtml, tests/test_forksoverknives.py
Recently fok recipes started including anchor tags in the category, linking to the category page. So, the category would look like:
"<a
href=\"https:\/\/www.forksoverknives.com\/recipes\/vegan-soups-stews\/\">Soups \&amp; Stews<\/a>"
Gourmand calls schema.category() to get the category, so this overrides that. Also, instead of leaving it:
Soups \&amp; Stews
import html and unescape it to return:
Soups & Stews
=> Fix issues with new forksoverknives category

recipe_scrapers/__init__.py
Very small one - I think there is a mistake in the type hint for the `**options` kwargs in `scrape_me`.
It manifests like this:
```
scraper = recipe_scrapers.scrape_me(url, wild_mode=True)
> (output of mypy)
> app/scraped_recipe/apis.py:32:81: error: Argument "wild_mode" to "scrape_me"
> has incompatible type "bool"; expected "Dict[str, Any]"  [arg-type]
>     ...stractScraper = recipe_scrapers.scrape_me(request.url, wild_mode=True)
>                                                                         ^~~~
```
The type hint for `**kwargs` is supposed to be the type of each individual kwarg - see the example at the bottom of [this section](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#functions) of the mypy docs.
I think there's another alternative, which is to use …
=> Fix options typehint

.pre-commit-config.yaml
The exciting post-v1.0 world of `mypy` Python type checking :tada: 
This is intended to resolve some [type check errors](https://github.com/hhursev/recipe-scrapers/actions/runs/4243084966/jobs/7375379611#step:5:48) that appeared in #735 that relate to creation of a [`requests.Session` object within a context manager](https://github.com/hhursev/recipe-scrapers/blob/d59ea12ff5d98b20cbd98eef5f77e01519276847/recipe_scrapers/bettybossi.py#L35) that doesn't play nicely with a combination of `types-requests` v2.28.11.14 and `mypy` prior to v1.0.0 (due to python/typeshed#9702, I think).
...that's the theory, anyway.  Let's see what continuous integration says about it.
=> pre-commit: update mypy version to v1.0.1

recipe_scrapers/eatingwell.py, tests/test_data/eatingwell.testhtml, tests/test_eatingwell.py
Context
the eatingwell.com recipe site was redesigned, with a slightly different HTML structure but now follows recipe schema that self.schema functions use 🥳.
Changes
* eatingwell.py member functions modified to use self.schema instead of custom parsing of the DOM
* test_eatingwell.py expected outputs changed to reflect outputs from schema
* eatingwell.testhtml updated to new website html document!
Thank you so much for the library! 😁
=> Fix outdated Eatingwell.com scraper leveraging schema

README.rst
There was a link with a broken format, it has been fixed.
=> Fixed link formatting

.github/workflows/unittests.yaml, tox.ini
Attempting to investigate and resolve some unit test failures for MacOS on Python versions 3.7 and 3.8 observed during #778.
=> Maintenance / investigation: reapply lxml workaround for MacOS unit test workflows

recipe_scrapers/_grouping_utils.py
This update adds a check to the `group_ingredients()` helper function that raises an exception if the number of ingredients found using the css selector in `group_ingredient()` does not match the number of ingredients return by `Scraper.ingredients()`.
This has been added based on feedback from @jayaddison in #799.
If I had opened this PR a bit earlier, then this would also have helped @jknndy in identifying the problem in #826 🤦
=> Grouping utils updates

.github/workflows/unittests.yaml
Save a few GitHub Actions continuous integration pennies by no longer running the unit test suite on Python 3.7 (that [reached end-of-life phase in June this year](https://peps.python.org/pep-0537/)).
=> continuous integration: unittests: Drop support for Python3.7

recipe_scrapers/goustojson.py, tests/test_goustojson.py
Another Gousto improvement.
This adds retrieving description from Gousto recipes, and fixes yield and prep time to reflect the ingredients. 
On Gousto's page they only provide time and servings for 2 servings by default, asking the user to double the ingredients for 4 servings. As we weren't doubling the ingredients (which would be quite involved), this will now instead return the total time and yield for 2 servings.
=> Gousto: Add description, fix time and yields.

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/waitrose.py, tests/test_data/waitrose.testhtml, tests/test_waitrose.py
=> Adds support for waitrose.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/eatwell101.py, tests/test_data/eatwell101.testhtml, tests/test_eatwell101.py
=> Adds support for Eatwell101.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/grouprecipes.py, tests/test_data/grouprecipes.testhtml, tests/test_grouprecipes.py
=> Add support for grouprecipes.com

recipe_scrapers/_utils.py
This should address this small oddity: https://github.com/hhursev/recipe-scrapers/commit/663baceec7659b9506d48bc0d919c6ed07ee8b53#diff-d13e1c74ee546f9fba5254f732e9e7de78fa9a0ffe6eb5788504d46c0c40ed18R75
(a `description` output containing the text `TomatoesÂ`)
cc @jknndy
=> Add UTF-8 two-byte hex 'C2 A0' encoding of non-breaking-space to 'normalize_string' replacements

docs/how-to-develop-scraper.md, tests/test_allrecipes.py, tests/test_farmhousedelivery_1.py, tests/test_foodandwine_1.py, tests/test_halfbakedharvest.py, tests/test_halfbakedharvest_groups.py, tests/test_heinzbrasil.py, tests/test_ig.py, tests/test_inspiralized.py
cc @jknndy - what do you reckon?
=> Refactor: use unittest.expectedFailure as a declarative indicator for single-instruction test recipes

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/grandfrais.py, tests/test_data/grandfrais.testhtml, tests/test_grandfrais.py
Grand Frais is a French supermarket specializing in fresh produce and world groceries, and offers recipes on its website (https://www.grandfrais.com/recettes/)
=> Adds support for www.grandfrais.com

recipe_scrapers/_utils.py, recipe_scrapers/nihhealthyeating.py, recipe_scrapers/tastykitchen.py, tests/library/test_utils.py, tests/test_kitchenstories.py, tests/test_panelinha_2.py, tests/test_weightwatchers.py
=> utils: get_minutes: return 'None' (empty) when no timing information is found in text

.github/workflows/coverage.yaml
=> ci: coverage workflow: pin to Python versions below 3.12

.github/workflows/linters.yaml
Follows-on-from #917 -- although in this case, I'm less confident that Python 3.12 is the cause of continuous integration failures.
Relates to #909.
=>  ci: coverage workflow: pin to Python versions below 3.12

generate.py, templates/test_scraper.py
@jayaddison let me know how this looks, pretty straight forward addition.
I was thinking about adding another feature here to skip generating a second scraper & innit entry if the hostname already exist. For generation of multiple tests (aka ingredient groups). Any opposition or should I throw something together?
=> Adds canonical_url to generate.py

recipe_scrapers/goustojson.py, tests/test_data/gousto.testjson, tests/test_goustojson.py
Sometimes the json obtained from gousto has duplicate ingredient entries but the label value in the duplicate is None. This fix checks the value of the label key and skips any that are None.
Fixes #931
=> goustojson scraper fix

.github/workflows/linters.yaml, .pre-commit-config.yaml
Follows-on-from #918, removing a version pin.
Relates to #909.
=> pre-commit: update flake8 to v6.1.0 - providing support for Python 3.12

recipe_scrapers/_utils.py, tests/test_data/hersheyland.com/herseyland.json, tests/test_data/kingarthurbaking.com/kingarthur.json, tests/test_data/myplate.gov/usdamyplate.json, tests/test_data/myrecipes.com/myrecipes.json, tests/test_data/ohsheglows.com/ohsheglows.json, tests/test_data/paninihappy.com/paninihappy.json
Adds functionality to the get_yields function to handle cases where the "serving" metric is dozen (#960) or batches. 
This may be an unwanted functionality in which case we can just close this without merge but wanted to take a shot at addressing the bug report but if this is something that could be beneficial going forward it could be expanded to handle piece(s), jar(s), cup(s), slice(s), etc...
Resolves #960
=> Updates get_yields util functionality to handle additional metrics

docs/how-to-develop-scraper.md
Previous command would throw an error for trying to use the "unknown option: -k". Command usage corrected and now matches the command mentioned in the README.
=> corrected shell command for scraper-specific unittest

tests/__init__.py
Prompted by @jayaddison's recent comment on #944, this changes how the test function for each scraper is built.
Currently, if an assertion fails for a scraper, the test function exists immediately and doesn't run any further tests for that scraper. With this change, each test is now run within a `unittest.subTest()` context manager, so that all the tests will run even if an assertion fails. 
As an example, I made two minor changes to the pickuplimes.json file to cause two of the tests to fail.
```
$ python -m unittest -k pickuplimes
F
======================================================================
FAIL: tests/test_data/pickuplimes.com/pickuplimes.json (tests.RecipeTestCase.tests/test_data/pickuplimes.com/pickuplimes.json)
------------------------------------------------------------- …
```
=> Run all tests for scraper even if an assertion fails

recipe_scrapers/_schemaorg.py, recipe_scrapers/_utils.py, recipe_scrapers/allrecipes.py, recipe_scrapers/receitasnestlebr.py, tests/library/test_utils.py, tests/test_data/arla.se/arla_2.json
The `_utils.get_minutes` method has a high McCabe cyclomatic complexity, meaning that [`flake8` would complain](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-max-complexity) about it if we didn't [suppress the relevant `C901` warning](https://github.com/hhursev/recipe-scrapers/blob/663b7500b57c6c51314c3c308c31be508749c6b2/recipe_scrapers/_utils.py#L63).
Although not perfect, a high complexity score is usually a good indicator that some code could be refactored into something cleaner.
I've wanted to try this for a while, and I'll see how far I get with this branch.  There are a few inter-dependencies (exception handling, plugins, zero-value handling, ...), not to mention that we only have a few tests per scraper, so a few experiments may be required along the way.
=> Refactor the utils.get_minutes method

recipe_scrapers/sallysbakingaddiction.py, tests/test_data/sallysbakingaddiction.com/sallysbakingaddiction.json
Adds the `cook_time`, `prep_time`, `description` and `cuisine` properties.
I'm a bit confused whether this scraper is necessary though since it doesn't override anything and wild mode seems to work fine? Looking at #617, is it more a case of "we know this works and can prove it with the tests"? Sorry if I'm missing something obvious, just trying to understand so I can better contribute :)
=> Add missing properties to Sally's Baking Addiction

tests/legacy/__init__.py, tests/legacy/test_goustojson.py
@Keyruu could you please take a look at this suggestion?
What I'd like to do here is to allow the tests to optionally expect specific header values from the scraper when it makes a request.
In the case of #1014 that would include the `Accept-Language` header, which should match the original HTML page.  It may also include the `Device-Type` header (if that's required).
=> tests: allow legacy tests to check for expected headers

recipe_scrapers/__init__.py, recipe_scrapers/_abstract.py, recipe_scrapers/foodnetwork.py
This PR fixes #1010 
As described in the issue, this commit https://github.com/hhursev/recipe-scrapers/commit/4fef338670142c3b4563f902ded1ade1f8001d0f#diff-5d1c0cbbdbecea7561f2fa87a9ecdd8bb896262f71727989caa4cf140b54cdeb changed the URL for foodnetwork from foodnetwork.com to foodnetwork.co.uk. Additionally, foodntwork.com now is blocking requests from "old" user-agents and this PR updates the user-agent header.
I left foodnetwork.co.uk as the "default" domain and added the capability to also reference foodnetwork.com the same way as hellofresh scraper supports multiple domains. Tests are passing and I tried the following URLs locally and they both work as expected:
```python
scraper = scrape_me('https://www.foodnetwork.com/recipes/alton-brown/shepherds-pie-recipe2-1942900', …
```
=> Added foodnetwork.com back

.pre-commit-config.yaml
Listed in #617 as a suggestion, and the `sphinx-lint` readme now provides good advice on how to enable it using `pre-commit`.
=> pre-commit: add sphinx-lint step

requirements-dev.txt
The version-range applied here excludes v5.1.1 of `lxml`, where removal of a non-unicode string type in https://github.com/lxml/lxml/commit/eba79343d0e7ad1ce40169f60460cdd4caa29eb3 causes problems for [v0.16 of `extruct`](https://github.com/scrapinghub/extruct/blob/85b5f0d19e2d4a6e1bb2e15068380e014df9bc98/extruct/xmldom.py#L12).  The version-range is applied for development dependencies (continuous integration, local development).
Ref: https://github.com/scrapinghub/extruct/issues/215
Relates to #1045 (but does not resolve it).
=> Development dependencies: limit to extruct-0.16-compatible lxml.

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/kitchenaidaustralia.py, tests/test_data/kitchenaid.com.au/kitchenaidaustralia_1.json, tests/test_data/kitchenaid.com.au/kitchenaidaustralia_1.testhtml
This PR adds support for KitchenAid Australia recipes. There was some `Recipe` schema support, however only for basic metadata. Ingredients, instructions, time and yield were all scraped manually.
`total_time()` was particularly difficult, as across different recipes there are different fields for time. The approach I took was to get all the time related fields from the summary and then use the last one as the total, which was the case in all the recipes I checked. If you think it is necessary I'm happy to add some test cases for this.
Resolves #1057
=> Add KitchenAid Australia

README.rst
The idea here is to provide some additional documentation about HTML-based scraping into the `v14` branch, so that deprecation warnings added by #1079 are easier for users to understand and resolve, and to ease the transition towards `v15` (where providing HTML is the recommended usage pattern).
Relates to #1022.
=> v14: README: add reference to a couple of HTTP clients.

pyproject.toml
Version `0.15.0` of `extruct` declared support for Python 3.10 and 3.11, so it seems worthwhile to upgrade our baseline dependency to that version or greater.
=> Dependencies: increase baseline 'extruct' version to >= 0.15.0

requirements-dev.txt
This includes [various improvements](https://github.com/getsentry/responses/blob/82d1e53f0ceee444c4208e19c2bad69e3a3780c0/CHANGES#L1-L77), including declared support up to Py3.12 while retaining support for Py3.8 as we provide here.
In practice our continuous integration has already been running since mid-February with this version; the change here is a strong-ish recommendation to use that version onwards during development.
=> Development dependencies: increase baseline responses version to >= 0.25.0

requirements-dev.txt
We haven't upgraded our dev baseline requirement for `coverage` for quite a while; but `pip` and other tools do generally install the latest-available version, and it has always been a version-or-greater spec.
That half-apology aside: there are _lots_ of improvements in [the `coverage` changelog](https://github.com/nedbat/coveragepy/blob/bc5e2d7453f9766a143243d9fa72b0acd75f517e/CHANGES.rst) since v4.5.1 - so many in fact that that file's content has been archived to the [project documentation website](https://coverage.readthedocs.io/en/latest/changes.html).
Python 3.8+ remains supported, and Python 3.11 and 3.12 are declared supported also.
=> Development dependencies: increase baseline 'coverage' version to >= 7.4.4

tests/__init__.py
A fairly nitpicky change, this one - and it doesn't affect the report output when running `python -m unittest`, so it's not expected to have much effect.
Basically the principle here is that a unit test requires at least one assertion to be made, so in cases where we know that we won't be making an assertion, we should skip the subtest creation.
Noticed during code review at https://github.com/hhursev/recipe-scrapers/pull/1061#discussion_r1584590732
=> Data-driven tests: create subtests only for optional fields with expectations.

recipe_scrapers/__init__.py, recipe_scrapers/creativecanning.py, tests/test_data/creativecanning.com/creativecanning.json, tests/test_data/creativecanning.com/creativecanning.testhtml
The idea for this refactor originates from code-review of #1116.
There are two motivations:
* Selection of a scraper should be possible based on the origin URL as input (this was already catered-for).
* Domain names and brands can be merged/acquired over time, so if two sites appear distinct in the view of a typical consumer -- even if they are known to be owned by the same entity, and present the same content -- then we should retain different scraper classes for each of them.  Internally they may re-use implementation (as is the case here).
=> Refactor: consistency: use a separate scraper classname per brandname.

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/jocooks.py, tests/test_data/jocooks.com/jocooks.json, tests/test_data/jocooks.com/jocooks.testhtml
This is a PR for recipe-scrapers to include recipes from jocooks. There was full schema support except for ingredient groups which had to be configured manually.
Resolves #1129
=> add jocooks.com scraper

pyproject.toml, requirements-dev.txt
A [new version of extruct](https://github.com/scrapinghub/extruct/releases/tag/v0.17.0) has been published which fixes https://github.com/hhursev/recipe-scrapers/issues/1045 which is the reason we pinned lxml. Bumping extruct allows us to use any lxml version again.
(fixes https://github.com/hhursev/recipe-scrapers/issues/1045)
=> fix(deps): bump extruct and remove lxml pin

README.rst
This is necessary because duplication of same-name (non-anonymous, single-trailing-underscore) hyperlinks is invalid rST syntax.
Resolves #1157.
=> README: Fixup: make variant-top-level-domain into anonymous hyperlinks.

recipe_scrapers/allrecipes.py, tests/test_data/allrecipes.com/allrecipescurated.json, tests/test_data/allrecipes.com/allrecipescurated.testhtml
AllRecipes changed their HTML structure, which breaks our workaround for pulling recipe ingredients. For more information, [see the bug report](https://github.com/hhursev/recipe-scrapers/issues/1154).
Since the class seems to be generated (a few other sites use a similar class name) I added a slightly more robust class selector, in case it ever changes again.
Fixes https://github.com/hhursev/recipe-scrapers/issues/1154
=> fix: AllRecipes Missing Ingredients

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/bakels.py, tests/test_data/bakels.co.uk/bakels.json, tests/test_data/bakels.co.uk/bakels.testhtml, tests/test_data/bakels.com.au/bakels_2.json
These recipes looked well-structured and useful to me while reviewing #1096 so I wanted to extend their support to their `.co.uk` domain.
Doing that seems to have uncovered a couple of other issues:
* Our `host` field might not be easily testable for non-default domains?
* The existing Bakels scraper may have some fragile `instructions` handling logic.
Resolves #1099.
cc @heathrampazis
=> Bakels: extend to add support for .co.uk domain.

recipe_scrapers/_schemaorg.py, tests/test_data/aflavorjournal.com/aflavorjournal_1.json, tests/test_data/aflavorjournal.com/aflavorjournal_2.json, tests/test_data/alexandracooks.com/alexandracooks_1.json, tests/test_data/alexandracooks.com/alexandracooks_2.json, tests/test_data/barefeetinthekitchen.com/barefeetinthekitchen_1.json, tests/test_data/barefeetinthekitchen.com/barefeetinthekitchen_2.json, tests/test_data/cafedelites.com/cafedelites_1.json, tests/test_data/cafedelites.com/cafedelites_2.json, tests/test_data/damndelicious.net/damndelicious_1.json, tests/test_data/damndelicious.net/damndelicious_2.json, tests/test_data/familyfoodonthetable.com/familyfoodonthetable_1.json, tests/test_data/familyfoodonthetable.com/familyfoodonthetable_2.json, tests/test_data/modernhoney.com/modernhoney_1.json, tests/test_data/momontimeout.com/momontimeout_1.json, tests/test_data/momontimeout.com/momontimeout_2.json, tests/test_data/recipegirl.com/recipegirl_1.json, tests/test_data/recipegirl.com/recipegirl_2.json, tests/test_data/savorynothings.com/savorynothings_1.json, tests/test_data/savorynothings.com/savorynothings_2.json, tests/test_data/thecookierookie.com/thecookierookie_1.json, tests/test_data/thecookierookie.com/thecookierookie_2.json, tests/test_data/thesaltymarshmallow.com/thesaltymarshmallow_1.json
Resolves #1175 
Modifies `ratings_count` to return integer values instead of floating-point & updates existing test cases
=> Fix ratings_count to return integer values

README.rst
* Move netiquette guidance to the top of the document.
* Clarification in terminology: refer to the ability to scrape webpages instead of sites.
* Place introductory instructions under their own dedicated section heading.
* Add a reference link to, and re-use, Python's recommended `pip` installation command-line.
* Fill in a missing step about opening a Python interpreter session.
Inspired-by / resolves #1180.
=> README: Update introductory section.

recipe_scrapers/__init__.py, tests/__init__.py, tests/library/test_exceptions.py
=> v14: make `wild_mode` opt-in (as usual) when using `scrape_html` interface.

README.rst
* Provide the list of HTTP client options as a list, as currently drafted in the V15 branch (f768a3ef4b873821061e88e03c105f2ba5c961df / #746).
* Remove some duplicative / incorrect code since the initial introductory examples now refer to `scrape_html` and use an HTTP client explicitly.
=> README: Adopt v15-style list for HTTP client hyperlinks.

docs/how-to-develop-scraper.md
A simple typo I found while reading the docs.
=> docs(how-to-develop-scraper.md): fix typo in sentence

requirements-dev.txt, tests/library/test_readme.py
Enables the unit test added in #1162 to run on all of the versions of Python supported by the library.
=> Tests: add package description metadata retrieval for Python 3.9 and earlier

.github/workflows/coverage.yaml, .github/workflows/linters.yaml, .github/workflows/unittests.yaml
Allows continuous integration to run for both the development mainline (`main` branch) and the maintained v14 (`v14` branch) branches.
If merged, this change will be merged into `v14` so that both branches contain identical workflow configurations.
=> ci: enable GitHub Actions workflows on the v14 branch

recipe_scrapers/_abstract.py
Adds the version of the `recipe-scrapers` library to the `HEADERS` user-agent field.  The format suggested here follows the [user-agent spec from RFC 7231](https://www.rfc-editor.org/rfc/rfc7231#section-5.5.3) (HTTP 1.1) -- there may be a better and/or more-recent alternative that I'm not aware of!
Resolves #1219
=> internals: add identifying library-plus-version string to `HEADERS`

recipe_scrapers/__init__.py, recipe_scrapers/_exceptions.py, recipe_scrapers/plugins/schemaorg_fill.py, tests/library/test_exceptions.py
Supports / unblocks #1228.
Resolves #1229.
=> schema.org-fill: raise a `RecipeSchemaNotFound` when no recipe metadata is found

.github/workflows/coverage.yaml
This is a cleanup for a version pin, added to workaround #909, that should have been applied alongside #919.
Relates-to commit 65f462e6e9e4734cad94fced153579bb4c17044e.
=> ci: coverage: remove Python version pin

.github/workflows/unittests.yaml, pyproject.toml
Follow-up to #1266:
* Enable unit testing using final release versions of Python 3.13
* Declare support for Python 3.13 using the package's Python [trove classifiers](https://github.com/pypa/trove-classifiers)
=> Maintenance: declare Python3.13 support

recipe_scrapers/usapears.py, tests/test_data/usapears.org/usapears.json, tests/test_data/usapears.org/usapears.testhtml
=> usapears: implement redundant-nutrient-value filtering

.github/workflows/unittests.yaml, tox.ini
As [noticed recently](https://github.com/hhursev/recipe-scrapers/pull/1308#discussion_r1807830905), the version of MacOS we're using for unit testing during GitHub Actions workflows is outdated; we're using MacOS 13 instead of the latest stable version labeled as `macos-latest`, which currently refers to MacOS 14.
This changeset updates the unit tests workflow to use `macos-latest` (MacOS 14).
I'm tempted to try removing some of the workarounds for MacOS in `tox.ini` at the same time; I think it depends on a sense about how many developers we may still have using MacOS 13 themselves.  It's probably worth _testing_ during this pull request -- whether it's sensible to remove the workarounds, assuming tests pass with them removed on MacOS 14, however, is a seperate question.
=> Maintenance: upgrade MacOS version for GitHub Actions unit testing

.github/workflows/publish.yaml, .github/workflows/test_publish.yaml
During the GitHub Actions package publication workflows, confirm that the commit-to-be-packaged exists on at least one of the release branches (currently: `main`, `v14`).
This is intended to prevent mistakes like the one described in #1272 from occurring in future.
=> GitHub Actions: releases: confirm commit exists on release branch

recipe_scrapers/_utils.py, tests/library/test_utils.py
=> Utils: reject empty input in `get_yields`

.github/workflows/unittests.yaml
Ref: https://github.com/actions/setup-python/tree/65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236#caching-packages-dependencies
=> ci: Enable `pip` caching for `setup-python` in GitHub Actions

recipe_scrapers/maangchi.py
Utilizes a regex string to find ingredient headers matching patterns like "Ingredients (serves _n_ to _m_)"
Example recipes
- https://www.maangchi.com/recipe/gimbap 
- https://www.maangchi.com/recipe/budae-jjigae
- https://www.maangchi.com/recipe/maeuntang
Unittests passing:
Any feedback or discussion is appreciated!
=> Fix(maangchi): use regex string to find ingredients header 

README.rst, docs/how-to-develop-scraper.md, pyproject.toml, requirements-dev.txt, tox.ini
=> Project: relocate development dependencies into 'pyproject.toml'

tests/library/test_utils.py
Discovered while attempting some test parallelization using `unittest-parallel` (that we previously used to run tests in the past; see #660) - this code failed when parallelism was enabled, and I think we can simplify it.
=> Tests: refactor: simplify assignment of util test fixtures

tests/__init__.py
In combination with #1342 and #1343, this enables the unit test suite to run using `unittest-parallel` (again, as it did in the past).
This improves the runtime duration of the tests from ~45 seconds to ~25 seconds on my local machine, and I anticipate that we'd achieve similar time savings during GitHub Actions workflows.
=> Tests: prepare test cases at module import-time

tests/library/test_main_methods.py
Without this fix applied, these tests could fail if Python warning filtering was configured in a way that interfered with the emission of the warnings - for example, when `PYTHONWARNINGS="ignore"` is configured as an environment variable.
By adding a `simplefilter` to always-emit `DeprecationWarning` notices, we can ensure that the test assertions apply correctly regardless of Python warning configuration.
=> Tests: correctness: ensure that deprecation warnings are always emitted when checking for them

.github/workflows/unittests.yaml
In `main` / v15, we run the continuous integration unit test suite using `unittest-parallel`, and this provides a significant speedup (see #1345).
Unfortunately when merging this back to `v14`, build errors occurred.  The cause seems to be that we have some [legacy tests](https://github.com/hhursev/recipe-scrapers/blob/bbb7e2d850eff6ec81b32228f1cfbf10de740dbb/tests/legacy/__init__.py) that perform class-level test setup (in a `setUpClass` method).
These have caused some problems with individual-test-level parallelism using `unittest-parallel` in the past (see craigahobbs/unittest-parallel#14), but there is now a `--level` argument that we can provide to specify how granularly parallelism should be applied.  By parallelizing at the `class` level instead, we can fix the problem.
=> v14: ci: enable unittest-parallel at class-level

.github/workflows/linters.yaml, tox.ini
Similar to #1339, but for the `linters` workflow in GitHub Actions.
Should contribute towards #1340, on aggregate.
=> ci: simplify 'linters' GitHub Actions workflow

LICENSE
Although this is a single-line change, it has a few details to explain:
* I've read in at least two places now (Linux Foundation training, and this blog post: https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects - that grouping copyright by a generic 'the project contributors' is a worthwhile practice for FOSS projects because they may have many and varying contributors over time).
* The first external contributions began in 2017 - but the next subsequent release I can find on PyPi is v5.0.0 in 2019.
* ~~As the blog post mentions, there could be some debate about what initiates publication for software - is it simply a push/merge to the host `git` repo?  I think a versioned and  package release is more appropriate generally, partly because pre-release …
=> LICENSE: add copyright notice line encompassing all contributors

.flake8, recipe_scrapers/_schemaorg.py, tests/library/test_schemaorg.py
As encountered during #1378, some recipe websites include multiple `Recipe` entities within individual HTML files.  This is valid; they could refer to aspects of multiple distinct recipes (for example, promoting other similar recipes), but in some cases they may also refer to the same, single recipe displayed on the page that we're interested in retrieving.
In that latter case (single recipe on the page, but presented using multiple `Recipe` entities), we currently use short-circuit logic that returns the first entity that we find.  If that's incomplete, then it could lead to recipe information being omitted.
The logic presented here is a draft; currently it assumes that all recipes that match the `@id` of the first `Recipe` found on the page -- or that all have an empty `@id` if the …
=> schema.org parser: allow aggregation from multiple Recipe entities

.markdownlint.json, docs/README.md, docs/how-to-develop-scraper.md, docs/in-depth-guide-ingredient-groups.md, docs/in-depth-guide-scraper-functions.md
Specifically:
- [`MD007`: Number of characters for list indentation](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md007---unordered-list-indentation)
- [`MD014`: Don't bother with `$` prefix for no-output `shell` examples](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output)
- [`MD026`: Section headings shouldn't end with punctuation](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md026---trailing-punctuation-in-header)
- [`MD029`: Numbered list items shouldn't be manually numbered](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md029---ordered-list-item-prefix)
- [`MD031`: Code blocks should have surrounding …
=> Documentation: apply a few `mdl` recommendations

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/ahealthysliceoflife.py, tests/test_data/ahealthysliceoflife.com/ahealthysliceoflife.json, tests/test_data/ahealthysliceoflife.com/ahealthysliceoflife.testhtml
=> Add "A Healthy Slice of Life" site

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/schoolofwok.py, tests/test_data/schoolofwok.co.uk/schoolofwok.json, tests/test_data/schoolofwok.co.uk/schoolofwok.testhtml
Resolves #1166
Added support for [schoolofwok.co.uk](https://schoolofwok.co.uk/). Recipe schema is not available, so most of the functions are custom-written. Specifically for ingredients, I noticed that there are two types for formatting - they are either listed using `<p> ... </p>` ([example](https://schoolofwok.co.uk/tips-and-recipes/simple-chicken-and-rice)) or `<li> ... </li>` ([example](https://schoolofwok.co.uk/tips-and-recipes/pork-and-noodles-stir-fry-ants-climbing-a-tree)), so my code is structured to take care of these two cases.
Feedback & suggestions for improvement are greatly appreciated. Thank you!
=> Added scraper for schoolofwok.co.uk

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/veroniquecloutier.py, tests/test_data/veroniquecloutier.com/veroniquecloutier.json, tests/test_data/veroniquecloutier.com/veroniquecloutier.testhtml
Resolves #1252
Added support for [veroniquecloutier.com](https://veroniquecloutier.com). Since this is a French recipe website, recipe schema is not available. Thus, I tried my best to identify patterns of where information is located. This is especially true for functions like `yields()`, `ingredients()`, and `instructions()`. I also chose not to implement `total_time()` since most of the recipes I looked at did not have this information.
Please let me know if there are any suggestions/feedback to make this better! Thank you in advance.
=> Added scraper for veroniquecloutier.com

.github/workflows/publish.yaml
Benefits:
- Improves security by removing non-expiring token
- Automatically generates signed digital attestations for distribution files
Links with more info:
- https://docs.pypi.org/trusted-publishers/
- https://github.com/marketplace/actions/pypi-publish#trusted-publishing
=> Use "Trusted Publishing" instead of the manual user/pass config.

generate.py
* Currently, generate.py tries to insert new `from ... import ...` statements after the first line (See https://github.com/hhursev/recipe-scrapers/issues/1259 and https://github.com/hhursev/recipe-scrapers/pull/1427#issuecomment-2526395409).
* It looks like the `node.level > 0` condition was added to skip the first item (`from __future__ import annotations`, which the generator considers to be a valid scraper class), but unfortunately `self.last_node = node` is still reached. The second time `__import()` is called, the first line is `self.last_node` and the new import is added beneath it.
* This PR moves the `node.level > 0` condition up into the parent `if` statement to avoid `self.last_node = node` from being called. Luckily, this doesn't impact the `elif` beneath it.
* I manually …
=> Fix __init__.py insertion bug

recipe_scrapers/cookwell.py, tests/test_data/cookwell.com/cookwell_1.json, tests/test_data/cookwell.com/cookwell_2.json
Cookwell.com only provides calorie information in the recipe metadata, but additional nutrition information is embedded in one of the page's scripts. This change searches the script tags for the matching information and extracts it. If it cannot find the information, it will default to the calorie only information provided in the metadata. I've tested this with a few random recipes from the site and observed it working as expected.
```
from urllib.request import urlopen
from recipe_scrapers import scrape_html
url = "https://cookwell.com/recipe/crispy-oven-fries"
html = urlopen(url).read().decode("utf-8")
scraper = scrape_html(html,url)
scraper.nutrients()
```
> {'calories': '970 calories', 'carbohydrateContent': '100 g', 'fatContent': '60 g', 'proteinContent': '12 g'}
```
...
url = …
```
=> Add better nutrition parsing for cookwell.com

recipe_scrapers/__init__.py
The urllib open was getting HTTP 403 (Forbidden) for some of the domains, examples https://addapinch.com/the-best-chocolate-cake-recipe-ever/ https://www.baking-sense.com/2024/03/08/coconut-layer-cake/.  Added a browser header that fixed the error
=> Added headers to the URLOpen Request

recipe_scrapers/aberlehome.py, tests/test_data/aberlehome.com/aberlehome_2.json
Instructions now return a list instead of string for `instructions_list`
=> Fix: aberlehome instruction 

recipe_scrapers/_utils.py
Accept both http://schema.org and https://schema.org for formatting.
Resolves a false return, below, in tests\test_data\aldi-nord.de\aldinord.json
```JSON
"dietary_restrictions": [
"http://schema.org/"
],
```
=> Update format_diet_name helper

recipe_scrapers/goodhousekeeping.py
Cuisine not present on site, no need for override
Keywords now exclude lines that contain `: ` (based on new html pull excluded from PR)
=> Update: goodhousekeeping
