recipe_scrapers/_abstract.py, recipe_scrapers/allrecipes.py
This diff makes the following changes:
-Adds a url() method to the scrape results
-Fixes the allrecipes.com scraper so it does not include the text "ADVERTISEMENT" in ingredients
-Adds some specific functionality to allrecipes.com. I'm not sure how you want to handle things that are on some recipe sites and not others, would welcome feedback here.
Each of these is in a separate commit, if you want to cherry-pick you're welcome to.
=> Various changes

README.md, recipe_scrapers/__init__.py, recipe_scrapers/nihhealthyeating.py, recipe_scrapers/tests/test_data/nihhealthyeating.testhtml, recipe_scrapers/tests/test_nihhealthyeating.py, tests.py
This is for the website https://healthyeating.nhlbi.nih.gov
I'm a little unclear about the actual title of the website.  It is hosted by the U.S. National Institute of Health's (NIH) National Heart, Lung and Blood Institute (NHLBI).  I've chosen "Healthy Eating" as its name, but I've also seen "Delicious Healthy Heart Recipes" and "Keep the Beat™ Heart Healthy Recipes".  Also, this website seems to be [composed of a few cookbooks](https://healthyeating.nhlbi.nih.gov/about.aspx).  Whatever the actual name, the scraper library doesn't really care, but it is nice to have good names for whomever is maintaining the code.
So, I went with what I thought was a simplest title "NIH Healthy Eating".  I thought that these other names should be noted.  If the name needs to be changed, let me know. …
=> Add scraper for NIH Healthy Eating website.

README.md, recipe_scrapers/_abstract.py
Added function to dictionary object containing link tag attributes. Updated the README.md to reflect changes and to describe dictionary object. No unit test were added the _abstract.py file is ignored.
=> Add support to returns links with attributes

README.md, recipe_scrapers/__init__.py, recipe_scrapers/inspiralized.py, recipe_scrapers/tests/test_data/inspiralized.testhtml, recipe_scrapers/tests/test_inspiralized.py, tests.py
=> Add in inspiralized support

README.md, recipe_scrapers/__init__.py, recipe_scrapers/tests/test_data/thehappyfoodie.testhtml, recipe_scrapers/tests/test_thehappyfoodie.py, recipe_scrapers/thehappyfoodie.py, tests.py
This is my first pull request ever, so I hope I'm doing everything right here.
=> Added scraper for http://thehappyfoodie.co.uk/

recipe_scrapers/yummly.py
I found that yummly do in fact include instructions on their website. I added code that should return a list of strings which comprise the instructions.
=> Add yummly instructions scraping

README.md, recipe_scrapers/__init__.py, recipe_scrapers/geniuskitchen.py, recipe_scrapers/tests/test_data/geniuskitchen.testhtml, recipe_scrapers/tests/test_geniuskitchen.py, tests.py
Added functionality and testing to scrape https://geniuskitchen.com
=> Added functionality and testing to scrape https://geniuskitchen.com

recipe_scrapers/__init__.py, recipe_scrapers/tests/test_data/wikicookbook.testhtml, recipe_scrapers/tests/test_wikicookbook.py, recipe_scrapers/wikicookbook.py, tests.py
=> Add scraper for: wikicookbook

recipe_scrapers/bonappetit.py, recipe_scrapers/foodnetwork.py, recipe_scrapers/hundredandonecookbooks.py, recipe_scrapers/jamieoliver.py, recipe_scrapers/paninihappy.py, recipe_scrapers/seriouseats.py, recipe_scrapers/steamykitchen.py, recipe_scrapers/tests/test_bonappetit.py, recipe_scrapers/tests/test_foodnetwork.py, recipe_scrapers/tests/test_hundredandonecookbooks.py, recipe_scrapers/tests/test_jamieoliver.py, recipe_scrapers/tests/test_paninihappy.py, recipe_scrapers/tests/test_seriouseats.py, recipe_scrapers/tests/test_steamykitchen.py, recipe_scrapers/tests/test_thepioneerwoman.py, recipe_scrapers/tests/test_thevintagemixer.py, recipe_scrapers/tests/test_whatsgabycooking.py, recipe_scrapers/thepioneerwoman.py, recipe_scrapers/thevintagemixer.py, recipe_scrapers/whatsgabycooking.py
Adds image scraping methods (with test coverage) for:
* 101cookbooks
* bonappetit
* foodnetwork
* jamieoliver
* paninihappy
* seriouseats
* steamykitchen
* thepioneerwoman
* thevintagemixer
* whatsgabycooking
=> Additional image retrieval implementation

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/bettycrocker.py, recipe_scrapers/tests/test_bettycrocker.py, recipe_scrapers/tests/test_data/bettycrocker.testhtml, tests.py
Added support for bettycrocker.com
=> Bettycrocker scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/ig.py, recipe_scrapers/tests/test_data/ig.testhtml, recipe_scrapers/tests/test_ig.py, tests.py
@hhursev one more, just a few to go :grin:
=> Adding support for https://receitas.ig.com.br (Fix #114)

recipe_scrapers/giallozafferano.py, recipe_scrapers/tests/test_data/giallozafferano.testhtml, recipe_scrapers/tests/test_giallozafferano.py
Hello,
I started writing a recipe scraper for giallozafferano website, and found out your great work.
So, first of all thank you very much :-) 
I realised that the recipe ratings from `https://ricette.giallozafferano.it/` are not retrieved correctly any more.
Here the fix I propose.
Thanks,
Chiara
=> Fix giallozafferano ratings

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/_utils.py, recipe_scrapers/mindmegette.py, recipe_scrapers/tests/test_data/mindmegette.testhtml, recipe_scrapers/tests/test_mindmegette.py, tests.py
This version supports a big [Hungarian recipe page](http://www.mindmegette.hu/).
Unfortunately the `get_minutes` function did not work for the Hungarian word `perc` (=minute in English) so I extended `TIME_REGEX` with `perc` and `óra` (=hour) in the `_utils` file.
BTW, I was so glad that the README contains an example for PRs, it was really helpful. Thank you!
=> Added support for mindmegette

recipe_scrapers/_schemaorg.py
Realized I had accidentally done this, hence the PR 😄
=> Stop setting self.format twice

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/kennymcgovern.py, recipe_scrapers/tests/test_data/kennymcgovern.testhtml, recipe_scrapers/tests/test_kennymcgovern.py, tests.py
=> Add support for kennymcgovern.com

recipe_scrapers/__init__.py, recipe_scrapers/_abstract.py, tests/__init__.py
Refs #148
Something that the package used to have. Put back exceptions handling as a decorator (utilizing the newer package structure).
Default exception handling can be switched off at will from devs using the package.
=> Option for default_exception_handling from the package

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/motherthyme.py, tests/test_data/motherthyme.testhtml, tests/test_motherthyme.py
Add scraper support for motherthyme.com and unittest
=> Add motherthyme.com scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/vegolosi.py, tests/test_data/vegolosi.testhtml, tests/test_vegolosi.py
Vegolosi.it scraper + testcase
=> Adding vegolosi scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/gousto.py, tests/test_data/gousto.testhtml, tests/test_gousto.py
#140 Added support for gousto.co.uk
=> Add gousto.co.uk scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/fitmencook.py, tests/test_data/fitmencook.testhtml, tests/test_fitmencook.py
Ugh, looks like linter was being a little aggressive with `__init__.py` (sorry for that!)
=> add support for fitmencook.com

recipe_scrapers/__init__.py, setup.py
This reverts commit e7e2d12e6dce8edc6d1bd882b61f81c6a01d693e.
Fixes #183.
=> Revert "Add PEP-396 module version number (#182)"

recipe_scrapers/_abstract.py, recipe_scrapers/bbcfood.py
Great package!
I just added this piece of information I find important.
=> Added author method for getting a recipe's author

tests/__init__.py, tests/test_fitmencook.py, tests/test_vegolosi.py
Encoding PR.  Ran a coverage test and everything seemed to work.
=> open *.testhtml now called with encoding = utf-8

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/nourishedbynutrition.py, tests/test_data/nourishedbynutrition.testhtml, tests/test_nourishedbynutrition.py
Adds support for Nourished By Nutrition (https://nourishedbynutrition.com/). It utilizes recipe schema.
=> Add nourishedbynutrition.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/nutritionbynathalie.py, tests/test_data/nutritionbynathalie.testhtml, tests/test_nutritionbynathalie.py
Adds support for recipes from Nutrition By Nathalie (https://www.nutritionbynathalie.com/blog). The content is scraped.
Test data extracted from https://www.nutritionbynathalie.com/single-post/2020/07/30/Mexican-Cauliflower-Rice
=> Add nutritionbynathalie.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/purelypope.py, tests/test_data/purelypope.testhtml, tests/test_purelypope.py
Adds support for PurelyPope (https://purelypope.com/). It uses recipe schema.
Test data from: https://purelypope.com/sweet-chili-brussel-sprouts/
=> Add purelypope.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/chefkoch.py, tests/test_chefkoch.py, tests/test_data/chefkoch.testhtml
Quickly added a parser for https://www.chefkoch.de/
URL used for tests: https://www.chefkoch.de/rezepte/1170311223132029/Hackbraten-supersaftig.html - yummy!
=> Add chefkoch.de parser

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/thenutritiouskitchen.py, tests/test_data/thenutritiouskitchen.testhtml, tests/test_thenutritiouskitchen.py
Uses recipe schema.
Test data from: https://thenutritiouskitchen.co/healthy-fig-pecan-crumble-bars/
=> Add support for thenutritiouskitchen.co

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/eatwhattonight.py, tests/test_data/eatwhattonight.testhtml, tests/test_eatwhattonight.py
Hey, I was using your package for my recipe scraper, and wanted to add support for this website that I am using. 
It uses recipe schema and the test recipe I used is: https://eatwhattonight.com/2020/08/ginger-soya-chicken/#wpzoom-recipe-card
=> Adding support for eatwhattonight.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/_abstract.py, recipe_scrapers/_factory.py, recipe_scrapers/_schemaorg.py
Wraps the `AbstractScrapper` into a factory, providing the basic implementation.
```
SchemaScraperFactory.generate(url)
```
=> Adds SchemaScraperFactory

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/hellofresh.py, recipe_scrapers/sunbasket.py, tests/test_data/sunbasket.testhtml, tests/test_sunbasket.py
Respectfully requesting addition of SunBasket recipe scraper.  Thank you for building such an awesome framework.
=> Add support for sunbasket.com recipe scraping

recipe_scrapers/__init__.py, recipe_scrapers/wholefoods.py, tests/test_data/wholefoods.testhtml, tests/test_wholefoods.py
Adding support for Whole Foods.
=> Adding support for wholefoods, which uses standard schema.

tests/test_data/innit.testhtml
Closes https://github.com/hhursev/recipe-scrapers/issues/247
=> Fixes Broken Unittests

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/kuchniadomowa.py, tests/test_data/kuchniadomowa.testhtml, tests/test_kuchniadomowa.py
Added a parser for kuchnia-domowa.pl
=> Kuchnia domowa

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/cuisineaz.py, tests/test_cuisineaz.py, tests/test_data/cuisineaz.testhtml
Credit goes to @EwenQuim who wrote the scraper and the tests. I just noticed that they hadn't responded in a while about the style maintenance and fixed it.
=> Add Cuisineaz support

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/cuisineaz.py, tests/test_cuisineaz.py, tests/test_data/cuisineaz.testhtml
Another popular french recipe website
=> Cuisineaz support

recipe_scrapers/nutritionbynathalie.py, tests/test_nutritionbynathalie.py
This change more loosly searches for content tags to allow more recipes to be successfully scraped on the site.
=> Increase the robustness of the nutritionbynathalie.com scraper

.pre-commit-config.yaml, recipe_scrapers/_abstract.py
Allows us to specify proxy server and timout options when calling scrape_me().
=> Adding proxy and timeout options to AbstractScraper.

recipe_scrapers/mindmegette.py, tests/test_data/mindmegette.testhtml, tests/test_mindmegette.py
Mindmegette had changed its layout, I fixed the scarper to align with it.
=> Fix mindmegette layout

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/streetkitchen.py, tests/test_data/streetkitchen.testhtml, tests/test_streetkitchen.py
This version supports another big Hungarian recipe page: https://streetkitchen.hu.
=> Add a scraper for https://streetkitchen.hu

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/atelierdeschefs.py, tests/test_atelierdeschefs.py, tests/test_data/atelierdeschefs.testhtml
I added a scraper for atelierdeschefs.fr.
The website has a schema but it fails on yields and instructions, so I used the soup attribute to scrape the relevant parts for those.
=> Add scrapers for atelierdeschefs

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/popsugar.py, tests/test_data/popsugar.testhtml, tests/test_popsugar.py
Scrapes the page. Test source: https://www.popsugar.com/food/Rainbow-Pasta-Food-Video-42193637
=> Add support for popsugar.com

README.rst, generate.py, recipe_scrapers/__init__.py, templates/scraper.py, templates/test_scraper.py
Adds the generate.py script to generate base classes to be used when adding a new scraper class to the library.
=> Feature: Scraper template generator

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/littlespicejar.py, tests/test_data/littlespicejar.testhtml, tests/test_littlespicejar.py
Tests: https://littlespicejar.com/crab-cake-bites/
=> Add support for littlespicejar.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/eatingbirdfood.py, tests/test_data/eatingbirdfood.testhtml, tests/test_eatingbirdfood.py
Tests: https://www.eatingbirdfood.com/curried-shakshuka/
=> Add support for eatingbirdfood.com

recipe_scrapers/__init__.py, recipe_scrapers/_schemaorg.py, recipe_scrapers/onehundredonecookbooks.py, tests/test_data/onehundredonecookbooks.testhtml, tests/test_onehundredonecookbooks.py
Minor code simplification and scraper
=> add OneHundredOneCookbooks

templates/test_scraper.py
Based on recommendation of @jayaddison
=> Adjust generate.py: assertCountEqual to assertEqual

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/indianhealthyrecipes.py, tests/test_data/indianhealthyrecipes.testhtml, tests/test_indianhealthyrecipes.py
Just a parser this time :)
Part of #206
=> add indianhealthyrecipes

README.rst
Note to self: generator doesn't necessarily add it.
=> add missing readme entry

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/marthastewart.py, tests/test_data/marthastewart.testhtml, tests/test_marthastewart.py
Scraper for marthastewart.com recipes
=> New Site: MarthaStewart.com

recipe_scrapers/_utils.py, recipe_scrapers/food52.py, tests/library/test_utils.py
Remove unneeded print statements from food52.py (new PR with commits fixed)
=> Remove debug print statement

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/_schemaorg.py, recipe_scrapers/cookinglight.py, tests/test_cookinglight.py, tests/test_data/cookinglight.testhtml
new site: cookinglight.com
for schemaorg, I was seeing:
```
"aggregateRating": {
"@type": "AggregateRating",
"itemReviewed": "Avocado, Black Bean, and Charred Tomato Bowl",
"bestRating": "5",
"worstRating": "1"
},
```
and so `ratings = ratings.get("ratingValue")` was returning None and that was being passed to `float()`
=> New Site: cookinglight.com + fix for _schemaorg.ratings

recipe_scrapers/bettycrocker.py, tests/test_bettycrocker.py, tests/test_data/bettycrocker.testhtml
simplified code: now uses self.schema in 4 methods
enhanced:
- instructions is now a \n-delimited string
- ratings provide count and rating
=> Enhancing Site: bettycrocker.com

recipe_scrapers/_utils.py
=> ignore case on time regex

recipe_scrapers/__init__.py, recipe_scrapers/_utils.py, recipe_scrapers/cucchiaio.py, tests/test_cucchiaio.py, tests/test_data/cucchiaio.testhtml
Just wanted to clear this out of the way and make sure it was added.
Credit to @tobiaghiraldini for #159. 
Closes #126
=> Add cucchiaio.it

recipe_scrapers/simplyrecipes.py, tests/test_data/simplyrecipes.testhtml
=> Update simplyrecipes instruction retrieval to match HTML source restructuring

recipe_scrapers/cucchiaio.py, tests/test_cucchiaio.py, tests/test_data/cucchiaio.testhtml
Updated the reference HTML and fixed / added a custom time implementation. I'm unsure about what the accurate time on the page is though since there are two sections with contradicting information.
Related to #351
=> Cucchiaio.it: Update and fix time

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/reishunger.py, tests/test_data/reishunger.testhtml, tests/test_reishunger.py
Related to #352 
This is the base implementation for single set of instructions.
@frudolph77 Have you seen ratings on that site?
=> Add reishunger.de scraper

recipe_scrapers/cucchiaio.py, tests/test_cucchiaio.py
As recommended by @rakicluca in #351.
A bit of a lazy change since I'll end up writing this for the v13 changes, but I thought I'd at least get it in.
=> Cucciaio.it: Use combined time

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/forksoverknives.py, tests/test_data/forksoverknives.testhtml, tests/test_forksoverknives.py
This commit adds a scraper for Forks Over Knives.
Fixes: #357
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
=> recipe_scrapers: add Forks Over Knives

recipe_scrapers/foodnetwork.py, tests/test_foodnetwork.py
Relevant:
https://github.com/hhursev/recipe-scrapers/issues/266
First time contributing so LMK anything else I need to change or do!
Thanks!
=> Use Schema in FoodNetwork scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/usdamyplate.py, tests/test_data/usdamyplate.testhtml, tests/test_usdamyplate.py
The recipes for this website are located here https://www.myplate.gov/myplate-kitchen/recipes
This is one of those websites that doesn't follow the schema.org/Recipe format.
Please let me know if I need to make any changes.
Thank you,
Micah
=> new scraper for USDA's MyPlate.gov website

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/joyfoodsunshine.py, tests/test_data/joyfoodsunshine.testhtml, tests/test_joyfoodsunshine.py
Added support for Joyfoodsunshine
created test with https://joyfoodsunshine.com/easy-homemade-pizza-dough/
=> Created scraper support for Joyfoodsunshine

recipe_scrapers/_exceptions.py, recipe_scrapers/nihhealthyeating.py, tests/test_data/nihhealthyeating.testhtml, tests/test_nih.py
See PR  #395 for discussion
This version raises `ElementNotFoundInHtml` for when image() content cannot be found at the URL.
=> NIHHealthyEating: Improvements - attempt 2

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/rainbowplantlife.py, tests/__init__.py, tests/test_data/rainbowplantlife.testhtml, tests/test_rainbowplantlife.py
=> Add scraper for rainbowplantlife.com

recipe_scrapers/_schemaorg.py, recipe_scrapers/hellofresh.py, tests/test_hellofresh.py
* Fixed missing `return` in image()
* Added support for nutrition info and updated test case
* Added some preprocessing to SchemaOrg.nutrients()
Ignores null and converts numbers to a string (how validator.schema.org does)
as normalize_string will choke on non-string values
=> Additional Hello Fresh fixes

recipe_scrapers/seriouseats.py, tests/test_seriouseats.py
Fixes author Not Implemented for Serious Eats.
=> Serious Eats author

recipe_scrapers/__init__.py, recipe_scrapers/zeitwochenmarkt.py, tests/test_data/zeitwochenmarkt.testhtml, tests/test_zeitwochenmarkt.py
Add scraper for Zeit Wochenmarkt (issue #427)
=> Zeitwochenmarkt

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/springlane.py, tests/test_data/springlane.testhtml, tests/test_springlane.py
Uses the default schema parser.
The example recipe is located here: https://www.springlane.de/magazin/rezeptideen/tiramisu-ohne-ei-und-ohne-alkohol/
=> Add support for springlane.de

recipe_scrapers/_schemaorg.py
Referenced in [this issue](https://github.com/hhursev/recipe-scrapers/issues/436)
=> Fix for instances where the type in the schema is stored as a list

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/sallysblog.py, tests/test_data/sallysblog.testhtml, tests/test_sallysblog.py
Hi,
I added support for the German recipe page "sallys-blog.de". I am not that used to developing python code, please let me know if something is wrong with my change. I am happy to rework if necessary.
=> Added support for sallys-blog.de

recipe_scrapers/_schemaorg.py, recipe_scrapers/allrecipes.py, recipe_scrapers/hellofresh.py, tests/library/test_exceptions.py, tests/test_allrecipes.py, tests/test_hellofresh.py
I have been using a few of the additional schema fields supported by HelloFresh and AllRecipes.  I also changed the _schema file just to make the categories/cuisine internal variable clearer.
=> Add scraper support for a few of the schema methods

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/realfoodtesco.py, tests/test_data/realfoodtesco.testhtml, tests/test_realfoodtesco.py
=> add realfoodtesco parser. 

recipe_scrapers/bettycrocker.py, tests/test_bettycrocker.py, tests/test_data/bettycrocker.testhtml
=> Fixups for bettycrocker instructions, ingredients, ratings fields

recipe_scrapers/__init__.py, recipe_scrapers/franzoesischkochen.py, tests/test_data/franzoesischkochen.testhtml, tests/test_franzoesischkochen.py
=> Add scraper for franzoesischkochen.de

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/kwestiasmaku.py, tests/test_data/kwestiasmaku.testhtml, tests/test_kwestiasmaku.py
=> add kwestiasmaku.com scraper (#480)

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/rezeptwelt.py, tests/test_data/rezeptwelt.testhtml, tests/test_rezeptwelt.py
This adds a scraper for https://rezeptwelt.de. Resolves #492 and addresses TandoorRecipes/recipes#1491.
I'm happy to receive feedback for improvements for this!
=> Add rezeptwelt.de scraper

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/valdemarsro.py, tests/test_data/valdemarsro.testhtml, tests/test_valdemarsro.py
This adds support for the Danish food blog https://www.valdemarsro.dk.
I'm a .NET developer by trade, this is my first attempt at Python, and I'd be happy to receive any feedback/criticism.
Also, this is my first GitHub contribution to an open source project, so please let me know if I've missed anything in the process.
Do note that in the description, I've joined two different sections, seperated by a dashed delimiter. The second part is (quite relevant) notes for the recipe, but I couldn't find a relevant section in which to place them.
=> Add Valdemarsro

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/sundpaabudget.py, tests/test_data/sundpaabudget.testhtml, tests/test_sundpaabudget.py
Add support for Danish food blog [Sund På Budget](https://sundpaabudget.dk).
=> Add support for Sund På Budget

recipe_scrapers/__init__.py, recipe_scrapers/lekkerensimpel.py, tests/test_data/lekkerensimpel.testhtml, tests/test_lekkerensimpel.py
This PR adds a scraper for dutch recipe site https://lekkerensimpel.com
=> Add scraper for lekkerensimpel.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/cookingcircle.py, tests/test_cookingcircle.py, tests/test_data/cookingcircle.testhtml
I found request #505 and gave it a try. I think it works well.
=> Add support for CookingCircle

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/fredriksfikaallas.py, tests/test_data/fredriksfikaallas.testhtml, tests/test_fredriksfikaallas.py
Added support for recipe site https://fredriksfika.allas.se
I´m new to python so I hope I made it correct.
=> Add support for fredriksfika.allas.se

recipe_scrapers/finedininglovers.py, tests/test_data/finedininglovers.testhtml, tests/test_finedininglovers.py
finedininglovers.com changed html a bit, and recipe title was parsed incorrectly.
I've updated the code, html test data and test case. I hope it's OK.
=> fix finedininglovers.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/bodybuilding.py, tests/test_bodybuilding.py, tests/test_data/bodybuilding.testhtml
I found request #468 and made support for it.
=> Add support bodybuilding.com

recipe_scrapers/cookingcircle.py, tests/test_cookingcircle.py
fix cookingcircle parser, return text instead of array, like in other parsers
=> fix cookingcircle instructions parsing

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/meljoulwan.py, tests/test_data/meljoulwan.testhtml, tests/test_meljoulwan.py
Found this request #453 
I hope the result is ok.
=> Add support meljoulwan.com

recipe_scrapers/thepioneerwoman.py, tests/test_data/thepioneerwoman.testhtml, tests/test_thepioneerwoman.py
This PR fixes the thepioneerwoman scraper since the site now embeds schema.org.
The issue was raised here: https://www.reddit.com/r/selfhosted/comments/ui6cny/tandoor_recipe_v14_released_shopping_importing/i7kkz9a/?context=3
=> fix thepioneerwoman scraper by using schema.org

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/lecker.py, tests/test_data/lecker.testhtml, tests/test_lecker.py
A new scraper for recipes on https://www.lecker.de.
Implements #541
=> New scraper for lecker.de

recipe_scrapers/allrecipes.py, recipe_scrapers/chefkoch.py, tests/test_allrecipes.py, tests/test_chefkoch.py
=> Add retrieval of 'description' field to allrecipes, chefkoch scrapers

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/imworthy.py, tests/test_data/imworthy.testhtml, tests/test_imworthy.py
Hi,  
This PR resolves #532 by adding support for I'm Worthy.com  
Thanks!  
Cyril
=> Add support for ImWorthy.com

setup.py
This PR update the AkisPetrezikis scraper that could not load the content of a recipe: the text of the `__NEXT_DATA__` tag needs to be retrieved, rather than the content of the tag itself.  
I'm not sure why exactly, maybe some dependencies were updated?  
I have the following, which is similar to what the CI runs :thinking:   
```text
Python 3.8.10
extruct==0.13.0
recipe_scrapers==14.5.0
requests==2.28.0
responses==0.21.0
```
This was tested by running the unit test, which was failing on my machine:
```
pytest -vv test/test_akispetrezikis.py
tests/test_akispetretzikis.py::TestAkisPetretzikisScraper::test_author FAILED               [  7%]
tests/test_akispetretzikis.py::TestAkisPetretzikisScraper::test_category FAILED             [ 15%] …
```
=> Update AkisPetrezikis scraper

recipe_scrapers/_abstract.py, recipe_scrapers/kptncook.py, tests/test_data/kptncook.testhtml, tests/test_data/kptncook.testjson, tests/test_kptncook.py
This PR aims to resolve the comments raised by @jayaddison in PR #503  which introduced the Kptncook scraper
=> Fix issues from review for the Kptncook scraper

recipe_scrapers/nihhealthyeating.py, templates/test_scraper.py, tests/test_nih.py
Added support for parsing additional information from healthyeating.nhlbi.nih.gov to include:
1. nutrients as an array
2. description text
3. Prep time text
4. Cook time text
5. Recipe source
=> Extended NIHHealthyEating 

recipe_scrapers/nutritionbynathalie.py
Small cleanup inspired by 6befc1d3973277141cce7695bbd8a984ad4b7686.
=> Refactor: remove use of 'while' loop

recipe_scrapers/nihhealthyeating.py
=> fix import from attr

recipe_scrapers/__init__.py, recipe_scrapers/smulweb.py, tests/test_data/smulweb.testhtml, tests/test_smulweb.py
Resolves #672
An item of feedback for #617 while implementing this: it's slightly annoying that the template scraper methods and template unit test methods are listed in different order.  That should be an easy improvement.
=> Add scraper for smulweb.nl

recipe_scrapers/__init__.py
Resolves https://github.com/hhursev/recipe-scrapers/pull/706#discussion_r1058962917
=> [v15] Fixup: restore Marmiton to registered-scrapers list

recipe_scrapers/plugins/schemaorg_fill.py, tests/test_forksoverknives.py
May resolve GourmandRecipeManager/gourmand#132.
=> SchemaOrgFillPlugin: add 'category' to the list of supported fields

recipe_scrapers/chefkoch.py, recipe_scrapers/eatsmarter.py, recipe_scrapers/emmikochteinfach.py, tests/test_chefkoch.py, tests/test_eatsmarter.py, tests/test_emmikochteinfach.py
(Eatsmarter doesn't work, so I return 0 as "time not present" value)
=> Added cook and prep time to emmikochteinfach, eatsmarter and chefkoch scrapers

recipe_scrapers/__init__.py, recipe_scrapers/forktospoon.py, recipe_scrapers/pressureluckcooking.py, tests/test_data/forktospoon.testhtml, tests/test_data/pressureluckcooking.testhtml, tests/test_forktospoon.py, tests/test_pressureluckcooking.py
New scraper for http://www.forktospoon.com
Includes scraper / test unit / test data
Test performed on https://forktospoon.com/air-fryer-parmesan-tomatoes/
=> New Scraper for http://www.forktospoon.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/chefnini.py, tests/test_chefnini.py, tests/test_data/chefnini.testhtml
New scraper for https://www.chefnini.com/
Includes scraper / test unit / test data
Test performed on https://www.chefnini.com/tagliatelles-carbonara/
=> Add support for chefnini.com

recipe_scrapers/usdamyplate.py
USDAMyPlate will get all the ingredients even if it is grouped.
=> Fixed Bug #729

recipe_scrapers/__init__.py
=> hellofresh: add support for Austrian top-level-domain

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/gesundaktiv.py, tests/test_data/gesundaktiv.testhtml, tests/test_gesundaktiv.py
Adding support for recipes of gesund-aktiv.com (https://www.gesund-aktiv.com/rezepte)
=> Added gesund-aktiv.com

recipe_scrapers/sallysblog.py, tests/test_sallysblog.py
=> sallys-blog: add support for image link retrieval

recipe_scrapers/mindmegette.py, tests/test_mindmegette.py
=> Fix host classmethod for mindmegette.hu

recipe_scrapers/__init__.py, recipe_scrapers/pickuplimes.py, tests/test_data/pickuplimes.testhtml, tests/test_pickuplimes.py
Add scraper for pickuplimes.com
Test html from https://www.pickuplimes.com/recipe/cinnamon-spiced-orange-thyme-mocktail-1258
=> Add support for pickuplimes.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/sobors.py, tests/test_data/sobors.testhtml, tests/test_sobors.py
=> Add support for sobors.hu

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/goodfooddiscoveries.py, tests/test_data/goodfooddiscoveries.testhtml, tests/test_goodfooddiscoveries.py
Added a parser for [Good Food Discoveries](https://goodfooddiscoveries.com/). I believe this resolves PR #768.
=> Good Food Discoveries Parser

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/vegetarbloggen.py, tests/test_data/vegetarbloggen.testhtml, tests/test_vegetarbloggen.py
=> Added support for vegetarbloggen.no

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/ministryofcurry.py, tests/test_data/ministryofcurry.testhtml, tests/test_ministryofcurry.py
Is there interest in having PRs like this added? I've got tons of websites that don't appear in the scrapers list but have schema enabled. I'll continue to add them assuming there is interest in expanding the scrapers included in the project.
=> Added support for ministryofcurry.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/tasteau.py, tests/test_data/tasteau_1.testhtml, tests/test_data/tasteau_2.testhtml, tests/test_tasteau_1.py, tests/test_tasteau_2.py
Including support for the grouping feature.
Resolves #359.
Resolves #808.
=> Added support for Taste.com.au

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/receitasnestlebr.py, tests/test_data/receitasnestlebr_1.testhtml, tests/test_receitasnestlebr_1.py
Resolves #108 
This site could support ingredient grouping.
Cuisine data was not available via schema or found in the HTML & a few of the methods required some data cleaning for the correct output.
=> Added support for receitasnestle.com.br/

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/number2pencil.py, tests/test_data/number2pencil_1.testhtml, tests/test_data/number2pencil_2.testhtml, tests/test_number2pencil_1.py, tests/test_number2pencil_2.py
Includes support for ingredient groups.
This site required some HTML scraping to be implemented as a fall back for the Author, Category and Description methods as the data was not available in the schema on all pages tested. 
Additionally the cuisine schema was not available on every page and was also not stored anywhere else in the html that I could find, as a result i added a fallback to a blank response
=> Added support for number-2-pencil.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/lifestyleofafoodie.py, tests/test_data/lifestyleofafoodie_1.testhtml, tests/test_data/lifestyleofafoodie_2.testhtml, tests/test_lifestyleofafoodie_1.py, tests/test_lifestyleofafoodie_2.py
Includes support for ingredient grouping
=> Adds support for lifestyleofafoodie.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/_utils.py, recipe_scrapers/saboresanjinomoto.py, tests/test_data/saboresanjinomoto_1.testhtml, tests/test_data/saboresanjinomoto_2.testhtml, tests/test_saboresanjinomoto_1.py, tests/test_saboresanjinomoto_2.py, tests/test_themodernproper.py
Resolves #111 
Includes support for ingredient grouping.
=> Added support for saboresajinomoto.com.br

recipe_scrapers/realsimple.py, tests/test_realsimple.py
Fixes for the bugs reported by @jbelluch , implemented their approach for both while maintaining schema as a fall back.
It appears the site changed their formatting so both the old & new approaches are needed. Checked against a few recipes and seems to be working fine. 
Resolves #838 
Resolves #837
=> Updates to Ingredient & Yield scrapers for RealSimple

recipe_scrapers/__init__.py, recipe_scrapers/tofoo.py, tests/test_data/tofoo_1.testhtml, tests/test_data/tofoo_2.testhtml, tests/test_tofoo_1.py, tests/test_tofoo_2.py
Includes ingredient grouping
Resolves #835
=> Adds support for tofoo.co.uk

recipe_scrapers/ig.py, recipe_scrapers/tudogostoso.py, tests/test_heinzbrasil.py, tests/test_ig.py, tests/test_tudogostoso.py
These weren't related to the goal of #852, so pulling them out into a separate changeset.
=> Miscellaneous minor fixups extracted from pull request #852

recipe_scrapers/nibbledish.py, tests/test_nibbledish.py
=> nibbledish: add a fallback ingredient list extraction method

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/plowingthroughlife.py, tests/test_data/plowingthroughlife_1.testhtml, tests/test_data/plowingthroughlife_2.testhtml, tests/test_plowingthroughlife_1.py, tests/test_plowingthroughlife_2.py
=> Adds support for plowingthroughlife.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/onceuponachef.py, tests/test_data/onceuponachef_1.testhtml, tests/test_data/onceuponachef_2.testhtml, tests/test_onceuponachef_1.py, tests/test_onceuponachef_2.py
Includes ingredient grouping support
=> Adds support for onceuponachef.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/fattoincasadabenedetta.py, tests/test_data/fattoincasadabenedetta.testhtml, tests/test_fattoincasadabenedetta.py
=> Adds support for fattoincasadabenedetta.it

recipe_scrapers/__init__.py, recipe_scrapers/norecipes.py, tests/test_data/norecipes_1.testhtml, tests/test_data/norecipes_2.testhtml, tests/test_norecipes_1.py, tests/test_norecipes_2.py
Includes support for ingredient grouping
=> Adds support for norecipes.com

recipe_scrapers/hellofresh.py, tests/test_hellofresh.py, tests/test_hellofresh_adhoc.py
Resolves #845 
Updated total_time to include prep_time & corrected associated test cases.
=> Updated total_time to include prep_time 

recipe_scrapers/_schemaorg.py, recipe_scrapers/addapinch.py, recipe_scrapers/bakingmischief.py, recipe_scrapers/bakingsense.py, recipe_scrapers/bowlofdelicious.py, recipe_scrapers/budgetbytes.py, recipe_scrapers/castironketo.py, recipe_scrapers/copykat.py, recipe_scrapers/ditchthecarbs.py, recipe_scrapers/fifteenspatulas.py, recipe_scrapers/norecipes.py, tests/test_addapinch_1.py, tests/test_budgetbytes.py, tests/test_maangchi.py
=> Add lookup for author in schema.org 'Person' entities listed on page

tests/test_chefsavvy.py, tests/test_thekitchencommunity.py, tests/test_vegetarbloggen.py
Follow-up to noticing a [similar pattern in an existing test](https://github.com/hhursev/recipe-scrapers/pull/891#discussion_r1353113063) as part of review of #891.
=> Refactor / cleanup: remove 'actual_instructions' variable from test modules

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/uitpaulineskeukennl.py, tests/test_data/uitpaulineskeukennl_1.testhtml, tests/test_data/uitpaulineskeukennl_2.testhtml, tests/test_uitpaulineskeukennl_1.py, tests/test_uitpaulineskeukennl_2.py
added dutch site https://uitpaulineskeuken.nl with 2 test files
=> added https://uitpaulineskeuken.nl

docs/in-depth-guide-ingredient-groups.md
A small addition of an example to the ingredient_grouping docs
=> Adds example to ingredient_grouping docs

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/cooktalk.py, tests/test_cooktalk_1.py, tests/test_cooktalk_2.py, tests/test_data/cooktalk_1.testhtml, tests/test_data/cooktalk_2.testhtml
=> Adds support for cook-talk.com

recipe_scrapers/bongeats.py, tests/test_bongeats.py, tests/test_data/bongeats.testhtml
I had added support for bongeats.com in #774 but they've recently changed their website's layout. This PR should make it work again.
=> Adapt to website changes for bongeats.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/williamssonoma.py, tests/test_data/williamssonoma_1.testhtml, tests/test_data/williamssonoma_2.testhtml, tests/test_williamssonoma_1.py, tests/test_williamssonoma_2.py
=> Adds support for williams-sonoma.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/ricetteperbimby.py, tests/test_data/ricetteperbimby.it/ricetteperbimby_1.json, tests/test_data/ricetteperbimby.it/ricetteperbimby_1.testhtml, tests/test_data/ricetteperbimby.it/ricetteperbimby_2.json, tests/test_data/ricetteperbimby.it/ricetteperbimby_2.testhtml
=> Adds support for ricetteperbimby.it

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/mundodereceitasbimby.py, tests/test_data/mundodereceitasbimby.com.pt/mundodereceitasbimby_1.json, tests/test_data/mundodereceitasbimby.com.pt/mundodereceitasbimby_1.testhtml, tests/test_data/mundodereceitasbimby.com.pt/mundodereceitasbimby_2.json, tests/test_data/mundodereceitasbimby.com.pt/mundodereceitasbimby_2.testhtml
=> Adds support for mundoreceitasbimby.com

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/eatliverun.py, recipe_scrapers/fitslowcookerqueen.py, recipe_scrapers/heatherchristo.py, tests/test_data/eatliverun.com/eatliverun.json, tests/test_data/eatliverun.com/eatliverun.testhtml, tests/test_data/fitslowcookerqueen.com/fitslowcookerqueen.json, tests/test_data/fitslowcookerqueen.com/fitslowcookerqueen.testhtml, tests/test_data/heatherchristo.com/heatherchristo.json, tests/test_data/heatherchristo.com/heatherchristo.testhtml
adds support for: 
- FitSlowCookerQueen.com
- HeatherChristo.com
- EatLiveRun.com
=> add support for several sites

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/strongrfastr.py, tests/test_data/strongrfastr.com/strongrfastr.json, tests/test_data/strongrfastr.com/strongrfastr.testhtml
=> Adds support for strongrfastr.com

recipe_scrapers/mob.py, tests/test_data/mob.co.uk/mob.json
=> fix(mob): updating to align with new website structure

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/recept.py, tests/test_data/recept.se/recept.json, tests/test_data/recept.se/recept.testhtml
=> Adds support for Recept.se

.pre-commit-config.yaml, recipe_scrapers/__init__.py, recipe_scrapers/_grouping_utils.py, recipe_scrapers/_utils.py, recipe_scrapers/coopse.py, recipe_scrapers/fitmencook.py, recipe_scrapers/nihhealthyeating.py, recipe_scrapers/thehappyfoodie.py, tests/__init__.py
=> Cleanup: apply a few py3.8+ cleanups based on suggestions by pyupgrade

recipe_scrapers/bowlofdelicious.py, recipe_scrapers/gimmesomeoven.py, recipe_scrapers/kochbar.py, recipe_scrapers/lovingitvegan.py, recipe_scrapers/minimalistbaker.py, recipe_scrapers/seriouseats.py, recipe_scrapers/thewoksoflife.py, tests/test_data/bowlofdelicious.com/bowlofdelicious.json, tests/test_data/gimmesomeoven.com/gimmesomeoven.json, tests/test_data/kochbar.de/kochbar.json, tests/test_data/lovingitvegan.com/lovingitvegan.json, tests/test_data/minimalistbaker.com/minimalistbaker.json, tests/test_data/seriouseats.com/seriouseats.json, tests/test_data/thewoksoflife.com/thewoksoflife.json
See [a downstream PR for more context](https://github.com/poundifdef/plainoldrecipe/pull/176), which is where I came across this.
This adds the `description` field for a few parsers that definitely support it. These are only ones in-common with the downstream app linked above, there are likely plenty more that could benefit from this.
This is broadly similar to #554
=> Add the 'description' field for seven existing parsers

recipe_scrapers/simplyrecipes.py, tests/test_data/simplyrecipes.com/simplyrecipes_1.json, tests/test_data/simplyrecipes.com/simplyrecipes_2.json
=> Adds prep_time & cook_time coverage to simplyrecipes

.pre-commit-config.yaml, recipe_scrapers/_grouping_utils.py, recipe_scrapers/kptncook.py, recipe_scrapers/mykitchen101.py, recipe_scrapers/weightwatchers.py
=> pre-commit: update dependency versions

recipe_scrapers/_grouping_utils.py, tests/library/test_grouping_utils.py
**_grouping_utils/score_sentence_similarity**
- Adjusted comments to outline more detail about what is completed in this function and relocate some comments.
- Some quick code cleanups and relocated the `len()` function for calculating the intersection size to the line where intersection is defined for a slight readability update
**_grouping_utils/best_match**
- Adjusted comments to outline more detail about what is completed in this function
- Refined the strategy for identifying the best match index by using a key function for comparision
**_grouping_utils/group_ingredients**
- Updated some of the comments to add context
- Changed some variable names for readability
**tests/_grouping__utils.py**
- Added tests covering other possible inputs
=> Refactor of _grouping_utils and associated test case updates

README.rst, docs/how-to-develop-scraper.md, generate.py, recipe_scrapers/__init__.py, recipe_scrapers/_utils.py, recipe_scrapers/kuchynalidla.py, tests/test_data/kuchynalidla.sk/kuchynalidla.json, tests/test_data/kuchynalidla.sk/kuchynalidla.testhtml
Hi,
Adding scraper for kuchynalidla.sk.
Also a few minor changes.
- rephrased unittest instruction for new parser as it was sa bit unclear
- added normalization for windows newlines `\r\n`
- added encoding when saving `html` for testing. The previous implementation just saved the byte stream that requests fetched and then upon opening it was decoded as `utf-8`. This does not work in all cases and caused me serious headaches. It should not be assumed that byted object fetched by requests is always `utf-8` encoded.
=> kuchynalidla.sk scraper

recipe_scrapers/halfbakedharvest.py, tests/test_data/halfbakedharvest.com/halfbakedharvest.json, tests/test_data/halfbakedharvest.com/halfbakedharvest_groups.json
Resolves #1050 
Adding support for a few methods that were missing from the HalfBakedHarvest scraper (e.g. `cook_time`, `prep_time`). Also expanded the relevant tests to cover these newly added methods.
=> Expanded scraper for HalfBakedHarvest and updated tests to match (#1050)

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/bestrecipes.py, tests/test_data/bestrecipes.com.au/bestrecipes.json, tests/test_data/bestrecipes.com.au/bestrecipes.testhtml
This PR adds support for bestrecipes.com.au, using https://www.bestrecipes.com.au/recipes/aussie-meat-pie-recipe-2/34l4qr5q as the test case.
Resolves https://github.com/hhursev/recipe-scrapers/issues/1047
=> Add bestrecipes.com.au

README.rst, docs/in-depth-guide-scraper-functions.md, recipe_scrapers/_abstract.py, recipe_scrapers/_schemaorg.py, recipe_scrapers/plugins/schemaorg_fill.py, tests/__init__.py, tests/library/test_utils.py, tests/test_data/acouplecooks.com/acouplecooks.json, tests/test_data/cookieandkate.com/cookieandkate.json, tests/test_data/feastingathome.com/feastingathome.json, tests/test_data/ica.se/ica.json, tests/test_data/livelytable.com/livelytable_2.json, tests/test_data/maangchi.com/maangchi.json, tests/test_data/myjewishlearning.com/myjewishlearning.json, tests/test_data/pinchofyum.com/pinchofyum.json, tests/test_data/receitas.globo.com/globo.json, tests/test_data/sallysbakingaddiction.com/sallysbakingaddiction.json, tests/test_data/simple-veganista.com/simpleveganista.json, tests/test_data/simplywhisked.com/simplywhisked.json, tests/test_data/theclevercarrot.com/theclevercarrot_1.json, tests/test_data/yummly.com/yummly.json
Adds [cookingMethod](https://schema.org/cookingMethod) as a possible output for schema based scrapers & updates associated docs / tests.
=> Adds Cooking_method as a possible output

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/whole30.py, tests/test_data/whole30.com/whole30.json, tests/test_data/whole30.com/whole30.testhtml
includes ingredient grouping
Resolves #1071
=> Adds support for Whole30

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/joythebaker.py, tests/test_data/joythebaker.com/joythebaker.json, tests/test_data/joythebaker.com/joythebaker.testhtml
This PR adds support for Joy the Baker recipes. There was some schema support for this site, although time fields were not supported and had to be scraped manually.
I implemented a custom fix for `total_time()`, and figured it would work for `prep_time()` and `cook_time()` as well, so I have added those too. Thankfully, the site labels each of these fields, which made it much easier to grab the relevant data. Additionally, some of the recipes do not have a 'time' field, so I have a check to prevent unwanted exceptions. Right now I have it returning None in this case, do let me know if that is incorrect behavior (and if I should add tests for this). 
Resolves #1083
=> Add Joy the Baker

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/mccormick.py, tests/test_data/mccormick.com/mccormick_1.json, tests/test_data/mccormick.com/mccormick_1.testhtml, tests/test_data/mccormick.com/mccormick_2.json, tests/test_data/mccormick.com/mccormick_2.testhtml
=> Adds support for mccormick.com

recipe_scrapers/jamieoliver.py, tests/test_data/jamieoliver.com/jamieoliver.json
Relates-to commit e8d70098eb3498cfa8cc1c92f488f22cf57d2081.
Resolves #1126.
=> jamieoliver: fixup for typo in image-retrieval code.

README.rst, recipe_scrapers/__init__.py
=> Fixup: add `nosalty` to supported-hosts dictionary.

recipe_scrapers/__init__.py
=> Fixup: don't emit a deprecation notice for 'options' due to a single keyword-argument of 'wild_mode'.

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/ottolenghibooks.py, tests/test_data/books.ottolenghi.co.uk/ottolenghibooks_1.json, tests/test_data/books.ottolenghi.co.uk/ottolenghibooks_1.testhtml, tests/test_data/books.ottolenghi.co.uk/ottolenghibooks_2.json, tests/test_data/books.ottolenghi.co.uk/ottolenghibooks_2.testhtml
Adds support for books.ottolenghi.co.uk
Some books have slightly different formatting. I have tested this with:
- Sweet
- Simple
- Shelf Love
- Plenty More
- Plenty
- Flavor
- Extra Good Things
I currently do not have access to:
- Nopi
- Jerusalem
- Falastin
- Cookbook
=> add ottolenghi books scraper

generate.py
All changes included have not been discussed. Happy to amend or close this all together if these are not changes we're interested in implementing. That said, I am specifically in favor of the improved `main()` making its way to release.
- Replaced the uses of `os` with `pathlib` for file & directory handling. This is primarily a change to improve the readability as it does not change any functionality.
- Moved paths into variables for improved readability.
- Improved the `main()` function to include clearer usage instructions and provided an example.
- Added a verbose success message after a run.
=> Refactor `generate.py` 

recipe_scrapers/arla.py, tests/test_data/arla.se/arla_1.json, tests/test_data/arla.se/arla_1.testhtml, tests/test_data/arla.se/arla_2.json, tests/test_data/arla.se/arla_2.testhtml
=> Fix: groupings for Arla

recipe_scrapers/gesundaktiv.py, tests/test_data/gesund-aktiv.com/gesundaktiv.json, tests/test_data/gesund-aktiv.com/gesundaktiv.testhtml
=> Fix: gesund-aktiv

.github/workflows/unittests.yaml, README.rst, pyproject.toml
Ref: https://peps.python.org/pep-0569/
=> Maintenance: remove support for Python3.8 that is reaching end-of-life

recipe_scrapers/timesofindia.py
=> timesofindia: search for ingredients only within ingredient-data container

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/spainonafork.py, tests/test_data/spainonafork.com/spainonafork_1.json, tests/test_data/spainonafork.com/spainonafork_1.testhtml, tests/test_data/spainonafork.com/spainonafork_2.json, tests/test_data/spainonafork.com/spainonafork_2.testhtml
=> Adds support for spainonafork

recipe_scrapers/themodernproper.py, tests/test_data/themodernproper.com/themodernproper.json
=> modernproper: removes nutrient titles from output

recipe_scrapers/thekitchn.py, tests/test_data/thekitchn.com/thekitchn.json
=> thekitchn: include definite article (`The`) in `site_name` result

.github/workflows/unittests.yaml
=> ci: refactor: remove GitHub Actions unit test workflow dependency on 'tox'

recipe_scrapers/sundpaabudget.py, tests/test_data/sundpaabudget.dk/sundpaabudget.json
=> sundpaabudget: remove support for nutritional information

recipe_scrapers/mccormick.py
=> Mccormick: Improve Instruction Handling

docs/in-depth-guide-html-scraping.md, recipe_scrapers/_abstract.py
For discussion / to help make clear what I'm suggesting in #1364.
=> AbstractScraper: provide attributes to override default metadata parsers

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/kitchendivas.py, tests/test_data/kitchendivas.com/kitchendivas_1.json, tests/test_data/kitchendivas.com/kitchendivas_1.testhtml, tests/test_data/kitchendivas.com/kitchendivas_2.json, tests/test_data/kitchendivas.com/kitchendivas_2.testhtml
=> Adds support for kitchendivas

README.rst, recipe_scrapers/__init__.py, recipe_scrapers/recetteplus.py, tests/test_data/recette.plus/recetteplus.json, tests/test_data/recette.plus/recetteplus.testhtml
=> Adds support for recette.plus

recipe_scrapers/jamieoliver.py
The existing method for scraping instructions yields no results. Gave it a shot to fix it.
=> Fix jamieoliver instructions

recipe_scrapers/foodrepublic.py, tests/test_data/foodrepublic.com/foodrepublic.json, tests/test_data/foodrepublic.com/foodrepublic.testhtml
Many fields now available via schema and new coverage
=> Update FoodRepublic 

recipe_scrapers/juliegoodwin.py, tests/test_data/juliegoodwin.com.au/juliegoodwin_1.json, tests/test_data/juliegoodwin.com.au/juliegoodwin_2.json
Refactored time extraction to use a consolidated extracting helper for line matching and separated the prep and cook time gathering to expand coverage.
=> Refactor time handling for JulieGoodwin

recipe_scrapers/__init__.py, recipe_scrapers/okokorecepten.py, tests/test_data/okokorecepten.nl/okokorecepten_1.json, tests/test_data/okokorecepten.nl/okokorecepten_1.testhtml, tests/test_data/okokorecepten.nl/okokorecepten_2.json, tests/test_data/okokorecepten.nl/okokorecepten_2.testhtml
=> Adds support for okokorecepten

recipe_scrapers/__init__.py, recipe_scrapers/kookjij.py, tests/test_data/kookjij.nl/kookjij_1.json, tests/test_data/kookjij.nl/kookjij_1.testhtml, tests/test_data/kookjij.nl/kookjij_2.json, tests/test_data/kookjij.nl/kookjij_2.testhtml
=> Adds support for KookJij

recipe_scrapers/__init__.py, recipe_scrapers/culy.py, tests/test_data/culy.nl/culy_1.json, tests/test_data/culy.nl/culy_1.testhtml, tests/test_data/culy.nl/culy_2.json, tests/test_data/culy.nl/culy_2.testhtml
=> Adds support for culy

recipe_scrapers/__init__.py, recipe_scrapers/wdr.py, tests/test_data/www1.wdr.de/wdr_1.json, tests/test_data/www1.wdr.de/wdr_1.testhtml, tests/test_data/www1.wdr.de/wdr_2.json, tests/test_data/www1.wdr.de/wdr_2.testhtml
They don't really seem to have a fixed format, so we might need to add some more heuristics in the future.
=> feat: add parser for wdr.de

recipe_scrapers/dagelijksekost.py
=> fix instruction detection for dagelijkse kost

recipe_scrapers/_schemaorg.py
Fixes https://github.com/hhursev/recipe-scrapers/issues/1491. Didn't add a test as I was not sure what the right place for it would be. Let me know and I can add one
=> Fix issue #1491, data that is not an object in json-ld @graph

recipe_scrapers/__init__.py, recipe_scrapers/ndr.py, tests/test_data/ndr.de/ndr_1.json, tests/test_data/ndr.de/ndr_1.testhtml, tests/test_data/ndr.de/ndr_2.json, tests/test_data/ndr.de/ndr_2.testhtml
=> Adds support for ndr.de

recipe_scrapers/tasteau.py, tests/test_data/taste.com.au/tasteau_1.json, tests/test_data/taste.com.au/tasteau_1.testhtml, tests/test_data/taste.com.au/tasteau_2.json, tests/test_data/taste.com.au/tasteau_2.testhtml
=> Fix: TasteAU instructions

recipe_scrapers/_utils.py, tests/test_data/acozykitchen.com/acozykitchen_1.json
@jknndy I updated `SERVE_REGEX_NUMBER` to optionally handle floats
Resolves #1603
=> fix get_yields handling of floats

recipe_scrapers/__init__.py, recipe_scrapers/kikkoman.py, tests/test_data/kikkoman.eu/kikkoman_1.json, tests/test_data/kikkoman.eu/kikkoman_1.testhtml, tests/test_data/kikkoman.eu/kikkoman_2.json, tests/test_data/kikkoman.eu/kikkoman_2.testhtml
=> Adds support for Kikkoman

recipe_scrapers/lekkerensimpel.py, tests/test_data/lekkerensimpel.com/lekkerensimpel_3.json, tests/test_data/lekkerensimpel.com/lekkerensimpel_4.json, tests/test_data/lekkerensimpel.com/lekkerensimpel_4.testhtml
=> Fix: Lekkerensimpel + updates

docs/contributing/in-depth-guide-scraper-functions.md, recipe_scrapers/_abstract.py, recipe_scrapers/plugins/exception_handling.py, recipe_scrapers/plugins/schemaorg_fill.py, recipe_scrapers/settings/default.py, tests/__init__.py, tests/library/test_utils.py
Reviews is not a field covered and should not be listed under existing methods/etc.
Related discussion in #1273
=> Remove references to `Reviews`

recipe_scrapers/__init__.py, recipe_scrapers/migusto.py, tests/test_data/migusto.migros.ch/migusto.json, tests/test_data/migusto.migros.ch/migusto.testhtml
Hi
I noticed, that images from https://migusto.migros.ch had a bad quality in Mealie. After some analysis i found that recipe-scrapers identifies the wrong image source(s). I do not know which one exactly (I have not dug into the code). But the images identified through wild_mode (schema) are all very small, which results in up-scaling in Mealie and therefore bad image quality.
I have identified, that a much better image is provided in the `<meta property="og:image" content="https:://high_quality_image.jpg">` tag.
This scraper therefore explicitly fetches the image from this tag.
I do not know, whether this approach is optimal, or if wild_mode should be optimized to prefer other images. But this solutions works for me. Thank you for considering to integrate it upstream.
Thank you also for …
=> Add scraper for migusto.migros.ch

recipe_scrapers/americastestkitchen.py, tests/test_data/americastestkitchen.com/americastestkitchen_1.json, tests/test_data/americastestkitchen.com/americastestkitchen_2.json, tests/test_data/americastestkitchen.com/americastestkitchen_3.json, tests/test_data/americastestkitchen.com/americastestkitchen_3.testhtml, tests/test_data/cookscountry.com/cookscountry.json, tests/test_data/cooksillustrated.com/cooksillustrated.json
=> fix: ATK image

recipe_scrapers/__init__.py, recipe_scrapers/chefjackovens.py, tests/test_data/chefjackovens.com/chefjackovens_1.json, tests/test_data/chefjackovens.com/chefjackovens_1.testhtml, tests/test_data/chefjackovens.com/chefjackovens_2.json, tests/test_data/chefjackovens.com/chefjackovens_2.testhtml
Resolves #1644 
& fixes small reordering error in init
=> Adds support for chefjackovens

recipe_scrapers/matprat.py, tests/test_data/matprat.no/matprat_3.json, tests/test_data/matprat.no/matprat_3.testhtml
Update to the ingredients method to cover additional page formats.
Not related to but discovered during review of bug report #1630
=> MatPrat: Ingredients update
